// =========================
// DUO 라이어 키워드 게임 — 키워드 풀 (v0.1, 80쌍)
// 페어 구성 원칙: 비슷하지만 명확히 다른 것
// 라이어가 시민 키워드인 척 하기엔 부담스럽고, 너무 다르면 즉시 들킴
// =========================

export const CATEGORIES = [
  { id: "food",    label: "음식",         emoji: "🍔" },
  { id: "celeb",   label: "연예인/캐릭터", emoji: "🎤" },
  { id: "job",     label: "직업",         emoji: "💼" },
  { id: "stuff",   label: "일상물건",      emoji: "📱" },
  { id: "meme",    label: "인터넷 밈",    emoji: "🤣" },
  { id: "animal",  label: "동물",         emoji: "🐶" },
  { id: "stream",  label: "스트리머/게임", emoji: "📺" },
  { id: "anime",   label: "애니/캐릭터",   emoji: "🎌" },
];

export const LIAR_KEYWORDS = {
  food: [
    ["치킨", "피자"],
    ["김밥", "토스트"],
    ["라면", "우동"],
    ["떡볶이", "국물떡볶이"],
    ["짜장면", "짬뽕"],
    ["햄버거", "핫도그"],
    ["초밥", "회덮밥"],
    ["갈비", "삼겹살"],
    ["비빔밥", "김치볶음밥"],
    ["치즈", "버터"],
    ["콜라", "사이다"],
    ["아이스크림", "빙수"],
    ["마라탕", "훠궈"],
    ["커피", "녹차"],
    ["붕어빵", "잉어빵"],
  ],
  celeb: [
    ["아이유", "박효신"],
    ["손흥민", "김민재"],
    ["BTS", "블랙핑크"],
    ["유재석", "강호동"],
    ["박명수", "정형돈"],
    ["뽀로로", "핑크퐁"],
    ["마리오", "루이지"],
    ["피카츄", "라이츄"],
    ["짱구", "흰둥이"],
    ["도라에몽", "도라미"],
    ["헐크", "토르"],
    ["아이언맨", "캡틴아메리카"],
    ["슈퍼맨", "배트맨"],
    ["미키마우스", "도널드덕"],
    ["라이언", "브라운"],
  ],
  job: [
    ["의사", "약사"],
    ["경찰", "검사"],
    ["교사", "교수"],
    ["가수", "배우"],
    ["프로그래머", "디자이너"],
    ["변호사", "판사"],
    ["요리사", "제빵사"],
    ["운전기사", "택배기사"],
    ["군인", "경호원"],
    ["미용사", "메이크업아티스트"],
    ["스트리머", "유튜버"],
    ["작가", "기자"],
  ],
  stuff: [
    ["폰", "태블릿"],
    ["노트북", "데스크탑"],
    ["펜", "연필"],
    ["책", "노트"],
    ["안경", "선글라스"],
    ["가방", "지갑"],
    ["손목시계", "알람시계"],
    ["양말", "스타킹"],
    ["우산", "양산"],
    ["테이블", "책상"],
    ["침대", "소파"],
    ["칫솔", "빗"],
    ["컵", "텀블러"],
    ["베개", "쿠션"],
    ["거울", "액자"],
  ],
  meme: [
    ["무야호", "무야유"],
    ["머쓱타드", "부끄타드"],
    ["어쩔티비", "저쩔티비"],
    ["킹받네", "빡친다"],
    ["알빠노", "노빠꾸"],
    ["갓생", "욜로"],
    ["인싸", "아싸"],
    ["폼", "클라스"],
    ["찐", "페이크"],
    ["갓", "킹"],
    ["띵작", "명작"],
    ["잼민이", "초딩"],
    ["햄최몇", "라최몇"],
    ["ㄹㅇ", "ㅈㅇ"],
    ["오운완", "오저치고"],
  ],
  animal: [
    ["강아지", "고양이"],
    ["사자", "호랑이"],
    ["코끼리", "코뿔소"],
    ["토끼", "햄스터"],
    ["곰", "판다"],
    ["펭귄", "오리"],
    ["닭", "꿩"],
    ["쥐", "다람쥐"],
    ["돌고래", "상어"],
    ["말", "얼룩말"],
    ["거북이", "자라"],
  ],
  // ============================================================
  // 스트리머/게임 — 한국 인터넷 문화 (2026년 기준)
  // 비슷하지만 명확히 다른 라이벌/대체 관계 위주
  // ============================================================
  stream: [
    // 플랫폼
    ["유튜브", "트위치"],
    ["치지직", "숲"],
    // 게임 — 한국 MMO/RPG
    ["로아", "메이플"],
    ["던파", "아이온"],
    ["검은사막", "TL"],
    ["리니지", "오딘"],
    ["원신", "명조"],
    ["디아블로", "패오"],
    // 게임 — 슈팅/AOS
    ["롤", "발로"],
    ["오버워치", "카운터"],
    ["펍지", "포트나이트"],
    ["배그", "에이펙스"],
    // 게임 — 파티/레이싱/RTS
    ["마크", "로블록스"],
    ["어몽어스", "폴가이즈"],
    ["카트라이더", "카러플"],
    ["스타1", "스타2"],
    ["엘든링", "다크소울"],
    // e스포츠
    ["페이커", "데프트"],
    ["T1", "젠지"],
    ["디플러스", "한화생명"],
    // 음식 (핫템)
    ["탕후루", "마라탕"],
    ["엽떡", "신전"],
    ["두끼", "죠스떡볶이"],
    ["민초", "치약"],
    ["흑백요리사", "백종원"],
    ["아샷추", "흑임자라떼"],
    // 카페 트렌드
    ["메가커피", "컴포즈"],
    ["빽다방", "이디야"],
    ["노티드", "카페어니언"],
    // V튜버/버추얼 그룹
    ["스텔라이브", "이세계아이돌"],
    ["홀로라이브", "니지산지"],
    ["플레이브", "하데스"],
    ["허니즈", "에스더"],
    // 스텔라이브 멤버 짝패 (일본식 풀네임 — 졸업 멤버 제외)
    ["아카네 리제", "시라유키 히나"],
    ["텐코 시부키", "네네코 마시로"],
    // 플레이브 멤버 짝패
    ["예준", "노아"],
    ["밤비", "하민"],
    // 스트리머 (게임/예능)
    ["우왁굳", "랄로"],
    ["탬탬버린", "이춘향"],
    ["풍월량", "한동숙"],
    ["침착맨", "주펄"],
    ["김도", "노가리"],
    ["보겸", "감스트"],
    ["룩삼", "양봉"],
    // 스트리머 (지식/경제/먹방/여행/헬스)
    ["슈카", "따효니"],
    ["슈카월드", "박종훈"],
    ["영국남자", "졸리"],
    ["곽튜브", "빠니보틀"],
    ["햄지", "쯔양"],
    ["슈기", "떵개떵"],
    ["김계란", "핏블리"],
    ["침착맨", "진용진"],
    // 이세돌 멤버 짝패 (다른 V튜버 그룹과 균형 맞춤)
    ["릴파", "주르르"],
    ["고세구", "비챤"],
    // 인터넷 트렌드
    ["쇼츠", "릴스"],
    ["디시", "아카라이브"],
    ["인스타", "트위터"],
    ["네이버블로그", "티스토리"],
  ],
  // ============================================================
  // 애니/만화 — 작품/캐릭터/장르
  // ============================================================
  anime: [
    // 작품 — 소년만화
    ["원피스", "나루토"],
    ["블리치", "헌터x헌터"],
    ["귀칼", "주술회전"],
    ["진격의거인", "약속의네버랜드"],
    ["체인소맨", "지옥락"],
    ["스파이패밀리", "최애의아이"],
    ["슬램덩크", "하이큐"],
    ["도쿄리벤저스", "블루록"],
    ["나의히어로아카데미아", "블랙클로버"],
    // 작품 — 이세계/판타지
    ["리제로", "무직전생"],
    ["오버로드", "전생슬라임"],
    ["프리렌", "단다단"],
    // 작품 — 일상/감성
    ["봇치더락", "케이온"],
    ["러브라이브", "아이돌마스터"],
    ["에반게리온", "건담"],
    ["스즈메", "너의이름은"],
    // 캐릭터 — 짝패
    ["렘", "람"],
    ["고죠", "게토"],
    ["루피", "조로"],
    ["나루토", "사스케"],
    ["아냐", "요르"],
    ["키리토", "아스나"],
    ["사쿠라", "히나타"],
    ["미카사", "아르민"],
    ["젠야", "이노스케"],
    ["탄지로", "네즈코"],
    ["우라라카", "츠유"],
    // 장르
    ["이세계", "학원물"],
    ["스포츠", "배틀물"],
    ["로맨스", "일상물"],
    ["호러", "미스터리"],
    ["판타지", "SF"],
    // 스튜디오/감독
    ["지브리", "신카이마코토"],
    ["MAPPA", "유포테이블"],
  ],
};

// =========================
// 다국어 wrapper (ko 그대로 + ja/en 신규)
// =========================
export const CATEGORIES_BY_LANG = {
  ko: CATEGORIES,
  ja: [
    { id: "food",    label: "食べ物",       emoji: "🍔" },
    { id: "celeb",   label: "芸能人/キャラ", emoji: "🎤" },
    { id: "job",     label: "職業",         emoji: "💼" },
    { id: "stuff",   label: "日常品",       emoji: "📱" },
    { id: "meme",    label: "ネットミーム",  emoji: "🤣" },
    { id: "animal",  label: "動物",         emoji: "🐶" },
    { id: "stream",  label: "配信/ゲーム",   emoji: "📺" },
    { id: "anime",   label: "アニメ/キャラ", emoji: "🎌" },
  ],
  en: [
    { id: "food",    label: "Food",          emoji: "🍔" },
    { id: "celeb",   label: "Celebrities",   emoji: "🎤" },
    { id: "job",     label: "Jobs",          emoji: "💼" },
    { id: "stuff",   label: "Things",        emoji: "📱" },
    { id: "meme",    label: "Internet Memes", emoji: "🤣" },
    { id: "animal",  label: "Animals",       emoji: "🐶" },
    { id: "stream",  label: "Streamers/Games", emoji: "📺" },
    { id: "anime",   label: "Anime/Chars",   emoji: "🎌" },
  ],
};

// 일본어 시드 (175쌍 — ko 그대로 번역)
export const LIAR_KEYWORDS_JA = {
  food: [
    ["チキン", "ピザ"],
    ["キンパ", "トースト"],
    ["ラーメン", "うどん"],
    ["トッポッキ", "汁トッポッキ"],
    ["ジャージャー麺", "チャンポン"],
    ["ハンバーガー", "ホットドッグ"],
    ["寿司", "海鮮丼"],
    ["カルビ", "サムギョプサル"],
    ["ビビンバ", "キムチチャーハン"],
    ["チーズ", "バター"],
    ["コーラ", "サイダー"],
    ["アイスクリーム", "かき氷"],
    ["麻辣湯", "火鍋"],
    ["コーヒー", "緑茶"],
    ["たい焼き", "鯉焼き"],
  ],
  celeb: [
    ["IU", "パク・ヒョシン"],
    ["ソン・フンミン", "キム・ミンジェ"],
    ["BTS", "BLACKPINK"],
    ["ユ・ジェソク", "カン・ホドン"],
    ["パク・ミョンス", "チョン・ヒョンドン"],
    ["ポロロ", "ピンクフォン"],
    ["マリオ", "ルイージ"],
    ["ピカチュウ", "ライチュウ"],
    ["クレヨンしんちゃん", "シロ"],
    ["ドラえもん", "ドラミ"],
    ["ハルク", "ソー"],
    ["アイアンマン", "キャプテン・アメリカ"],
    ["スーパーマン", "バットマン"],
    ["ミッキーマウス", "ドナルドダック"],
    ["ライアン", "ブラウン"],
  ],
  job: [
    ["医者", "薬剤師"],
    ["警察官", "検事"],
    ["教師", "教授"],
    ["歌手", "俳優"],
    ["プログラマー", "デザイナー"],
    ["弁護士", "裁判官"],
    ["料理人", "パン職人"],
    ["運転手", "配達員"],
    ["軍人", "ボディガード"],
    ["美容師", "メイクアップアーティスト"],
    ["配信者", "YouTuber"],
    ["作家", "記者"],
  ],
  stuff: [
    ["スマホ", "タブレット"],
    ["ノートPC", "デスクトップ"],
    ["ペン", "鉛筆"],
    ["本", "ノート"],
    ["メガネ", "サングラス"],
    ["カバン", "財布"],
    ["腕時計", "目覚まし時計"],
    ["靴下", "ストッキング"],
    ["傘", "日傘"],
    ["テーブル", "机"],
    ["ベッド", "ソファ"],
    ["歯ブラシ", "クシ"],
    ["コップ", "タンブラー"],
    ["枕", "クッション"],
    ["鏡", "額縁"],
  ],
  meme: [
    ["ムヤホー", "ムヤユー"],
    ["モッスクタード", "ブックタード"],
    ["オッチョルテレビ", "チョッチョルテレビ"],
    ["キレる", "ムカつく"],
    ["アルパノ", "ノパック"],
    ["神生(カッセン)", "YOLO"],
    ["陽キャ", "陰キャ"],
    ["フォーム", "クラス"],
    ["本物", "フェイク"],
    ["神", "キング"],
    ["神作", "名作"],
    ["クソガキ", "小学生"],
    ["ハム最高", "ラー最高"],
    ["リアル", "本気"],
    ["今日の運動完了", "今日も貯金成功"],
  ],
  animal: [
    ["犬", "猫"],
    ["ライオン", "トラ"],
    ["象", "サイ"],
    ["ウサギ", "ハムスター"],
    ["クマ", "パンダ"],
    ["ペンギン", "アヒル"],
    ["ニワトリ", "キジ"],
    ["ネズミ", "リス"],
    ["イルカ", "サメ"],
    ["馬", "シマウマ"],
    ["カメ", "スッポン"],
  ],
  stream: [
    ["YouTube", "Twitch"],
    ["CHZZK", "SOOP"],
    ["ロアー", "メイプル"],
    ["ダンファ", "アイオン"],
    ["黒い砂漠", "TL"],
    ["リネージュ", "オーディン"],
    ["原神", "鳴潮"],
    ["ディアブロ", "パスオブエグザイル"],
    ["LoL", "VALORANT"],
    ["オーバーウォッチ", "カウンター"],
    ["PUBG", "フォートナイト"],
    ["BG", "Apex"],
    ["Minecraft", "Roblox"],
    ["Among Us", "Fall Guys"],
    ["カートライダー", "カートラッシュ"],
    ["スタクラ1", "スタクラ2"],
    ["エルデンリング", "ダークソウル"],
    ["Faker", "Deft"],
    ["T1", "Gen.G"],
    ["DK", "ハンファ"],
    ["タンフール", "麻辣湯"],
    ["ヨプトッ", "シンジョン"],
    ["トゥッキ", "ジョーズトッポッキ"],
    ["ミントチョコ", "歯磨き粉"],
    ["黒白料理人", "ペク・ジョンウォン"],
    ["アショッチュ", "黒ごまラテ"],
    ["メガコーヒー", "Compose"],
    ["ペクタバン", "Ediya"],
    ["ノティド", "カフェオニオン"],
    ["StellaLive", "isegye Idol"],
    ["ホロライブ", "にじさんじ"],
    ["プレイブ", "Hades"],
    ["Honeyz", "Esther"],
    ["アカネ・リゼ", "シラユキ・ヒナ"],
    ["テンコ・シブキ", "ネネコ・マシロ"],
    ["イェジュン", "ノア"],
    ["バンビ", "ハミン"],
    ["ウワククッ", "ラルロ"],
    ["テムテムバリン", "イ・チュニャン"],
    ["プンウォルリャン", "ハン・ドンスク"],
    ["チムチャクマン", "ジュポル"],
    ["キム・ド", "ノガリ"],
    ["ボギョム", "ガムストゥ"],
    ["ルクサム", "ヤンボン"],
    ["シュカ", "ッタヒョニ"],
    ["シュカワールド", "パク・ジョンフン"],
    ["イギリス男子", "ジョリー"],
    ["クァクチューブ", "パニボトル"],
    ["ヘムジ", "ツヤン"],
    ["シュギ", "ットンゲットン"],
    ["キム・ゲラン", "Fitvely"],
    ["チムチャクマン", "ジン・ヨンジン"],
    ["リルパ", "ジュルル"],
    ["ゴセグ", "ビチャン"],
    ["Shorts", "Reels"],
    ["DC", "アーカライブ"],
    ["Instagram", "Twitter"],
    ["NAVERブログ", "Tistory"],
  ],
  anime: [
    ["ONE PIECE", "NARUTO"],
    ["BLEACH", "HUNTER×HUNTER"],
    ["鬼滅の刃", "呪術廻戦"],
    ["進撃の巨人", "約束のネバーランド"],
    ["チェンソーマン", "地獄楽"],
    ["SPY×FAMILY", "推しの子"],
    ["スラムダンク", "ハイキュー!!"],
    ["東京リベンジャーズ", "ブルーロック"],
    ["僕のヒーローアカデミア", "ブラッククローバー"],
    ["Re:ゼロ", "無職転生"],
    ["オーバーロード", "転生したらスライムだった件"],
    ["葬送のフリーレン", "ダンダダン"],
    ["ぼっち・ざ・ろっく!", "けいおん!"],
    ["ラブライブ!", "アイドルマスター"],
    ["エヴァンゲリオン", "ガンダム"],
    ["すずめの戸締まり", "君の名は。"],
    ["レム", "ラム"],
    ["五条", "夏油"],
    ["ルフィ", "ゾロ"],
    ["ナルト", "サスケ"],
    ["アーニャ", "ヨル"],
    ["キリト", "アスナ"],
    ["サクラ", "ヒナタ"],
    ["ミカサ", "アルミン"],
    ["善逸", "伊之助"],
    ["炭治郎", "禰豆子"],
    ["麗日", "梅雨"],
    ["異世界", "学園物"],
    ["スポーツ", "バトル物"],
    ["ロマンス", "日常物"],
    ["ホラー", "ミステリー"],
    ["ファンタジー", "SF"],
    ["ジブリ", "新海誠"],
    ["MAPPA", "ufotable"],
  ],
};

// 영어 시드 (175쌍 — ko 그대로 번역)
export const LIAR_KEYWORDS_EN = {
  food: [
    ["Chicken", "Pizza"],
    ["Kimbap", "Toast"],
    ["Ramen", "Udon"],
    ["Tteokbokki", "Soupy Tteokbokki"],
    ["Jajangmyeon", "Jjamppong"],
    ["Hamburger", "Hot dog"],
    ["Sushi", "Sashimi bowl"],
    ["Galbi", "Samgyeopsal"],
    ["Bibimbap", "Kimchi fried rice"],
    ["Cheese", "Butter"],
    ["Coke", "Sprite"],
    ["Ice cream", "Bingsu"],
    ["Mala Tang", "Hot Pot"],
    ["Coffee", "Green tea"],
    ["Bungeoppang", "Ingeoppang"],
  ],
  celeb: [
    ["IU", "Park Hyo-shin"],
    ["Son Heung-min", "Kim Min-jae"],
    ["BTS", "BLACKPINK"],
    ["Yoo Jae-suk", "Kang Ho-dong"],
    ["Park Myung-soo", "Jeong Hyeong-don"],
    ["Pororo", "Pinkfong"],
    ["Mario", "Luigi"],
    ["Pikachu", "Raichu"],
    ["Crayon Shin-chan", "Shiro"],
    ["Doraemon", "Dorami"],
    ["Hulk", "Thor"],
    ["Iron Man", "Captain America"],
    ["Superman", "Batman"],
    ["Mickey Mouse", "Donald Duck"],
    ["Ryan", "Brown"],
  ],
  job: [
    ["Doctor", "Pharmacist"],
    ["Police officer", "Prosecutor"],
    ["Teacher", "Professor"],
    ["Singer", "Actor"],
    ["Programmer", "Designer"],
    ["Lawyer", "Judge"],
    ["Chef", "Baker"],
    ["Driver", "Delivery driver"],
    ["Soldier", "Bodyguard"],
    ["Hairdresser", "Makeup artist"],
    ["Streamer", "YouTuber"],
    ["Writer", "Reporter"],
  ],
  stuff: [
    ["Phone", "Tablet"],
    ["Laptop", "Desktop"],
    ["Pen", "Pencil"],
    ["Book", "Notebook"],
    ["Glasses", "Sunglasses"],
    ["Bag", "Wallet"],
    ["Wristwatch", "Alarm clock"],
    ["Socks", "Stockings"],
    ["Umbrella", "Parasol"],
    ["Table", "Desk"],
    ["Bed", "Sofa"],
    ["Toothbrush", "Comb"],
    ["Cup", "Tumbler"],
    ["Pillow", "Cushion"],
    ["Mirror", "Picture frame"],
  ],
  meme: [
    ["Muyaho", "Muyayu"],
    ["Mussktard", "Bukkutard"],
    ["Eojjeolttibi", "Jeojjeolttibi"],
    ["King-batne (Pissed)", "Ppakchinda (Angry)"],
    ["Alppano (Who cares)", "Nopppakku (No backing down)"],
    ["Gat-saeng (God life)", "YOLO"],
    ["Insa (Insider)", "Assa (Outsider)"],
    ["Form", "Class"],
    ["Real", "Fake"],
    ["God", "King"],
    ["Ddeungjak (Masterpiece)", "Myeongjak (Classic)"],
    ["Jaemmini (Brat)", "Choding (Elementary kid)"],
    ["Hammoeimyeoch", "Ramoeimyeoch"],
    ["ㄹㅇ (Real)", "ㅈㅇ (For real)"],
    ["Owanwan (Today's workout done)", "Ojeochigo (Today's saving done)"],
  ],
  animal: [
    ["Dog", "Cat"],
    ["Lion", "Tiger"],
    ["Elephant", "Rhino"],
    ["Rabbit", "Hamster"],
    ["Bear", "Panda"],
    ["Penguin", "Duck"],
    ["Chicken", "Pheasant"],
    ["Mouse", "Squirrel"],
    ["Dolphin", "Shark"],
    ["Horse", "Zebra"],
    ["Turtle", "Soft-shell turtle"],
  ],
  stream: [
    ["YouTube", "Twitch"],
    ["CHZZK", "SOOP"],
    ["Lost Ark", "MapleStory"],
    ["Dungeon Fighter", "Aion"],
    ["Black Desert", "TL"],
    ["Lineage", "Odin"],
    ["Genshin", "Wuthering Waves"],
    ["Diablo", "Path of Exile"],
    ["LoL", "Valorant"],
    ["Overwatch", "Counter-Strike"],
    ["PUBG", "Fortnite"],
    ["Battlegrounds", "Apex"],
    ["Minecraft", "Roblox"],
    ["Among Us", "Fall Guys"],
    ["KartRider", "KartRush"],
    ["StarCraft 1", "StarCraft 2"],
    ["Elden Ring", "Dark Souls"],
    ["Faker", "Deft"],
    ["T1", "Gen.G"],
    ["DK", "Hanwha Life"],
    ["Tanghulu", "Mala Tang"],
    ["Yeoptteok", "Shinjeon"],
    ["Dukki", "Jaws Tteokbokki"],
    ["Mint Choco", "Toothpaste"],
    ["Black & White Chef", "Paik Jong-won"],
    ["Ashotchu", "Black Sesame Latte"],
    ["Mega Coffee", "Compose"],
    ["Paik's Coffee", "Ediya"],
    ["Knotted", "Cafe Onion"],
    ["Stellive", "Isegye Idol"],
    ["Hololive", "Nijisanji"],
    ["Plave", "Hades"],
    ["Honeyz", "Esther"],
    ["Akane Lize", "Shirayuki Hina"],
    ["Tenko Shibuki", "Neneko Mashiro"],
    ["Yejun", "Noah"],
    ["Bamby", "Hamin"],
    ["Woowakgood", "Lal-lo"],
    ["Tamtamburin", "Lee Chun-hyang"],
    ["Pungwolryang", "Han Dong-suk"],
    ["Chimchakman", "Jupol"],
    ["Kim Do", "Nogari"],
    ["Bogyeom", "Gamstu"],
    ["Looksam", "Yangbong"],
    ["Shuka", "Ttahyoni"],
    ["Shukaworld", "Park Jong-hoon"],
    ["English Bro", "Jolly"],
    ["Gwakku-tube", "Pani Bottle"],
    ["Hamzy", "Tzuyang"],
    ["Shugi", "Ttoenggaeddoeng"],
    ["Kim Gyeran", "Fitvely"],
    ["Chimchakman", "Jin Yong-jin"],
    ["Lilpa", "Jururu"],
    ["Gosegu", "Vichan"],
    ["Shorts", "Reels"],
    ["DCInside", "Arca Live"],
    ["Instagram", "Twitter"],
    ["NAVER Blog", "Tistory"],
  ],
  anime: [
    ["One Piece", "Naruto"],
    ["Bleach", "Hunter x Hunter"],
    ["Demon Slayer", "Jujutsu Kaisen"],
    ["Attack on Titan", "Promised Neverland"],
    ["Chainsaw Man", "Hell's Paradise"],
    ["Spy x Family", "Oshi no Ko"],
    ["Slam Dunk", "Haikyu!!"],
    ["Tokyo Revengers", "Blue Lock"],
    ["My Hero Academia", "Black Clover"],
    ["Re:Zero", "Mushoku Tensei"],
    ["Overlord", "That Time I Got Reincarnated as a Slime"],
    ["Frieren", "Dandadan"],
    ["Bocchi the Rock!", "K-On!"],
    ["Love Live!", "The iDOLM@STER"],
    ["Evangelion", "Gundam"],
    ["Suzume", "Your Name"],
    ["Rem", "Ram"],
    ["Gojo", "Geto"],
    ["Luffy", "Zoro"],
    ["Naruto", "Sasuke"],
    ["Anya", "Yor"],
    ["Kirito", "Asuna"],
    ["Sakura", "Hinata"],
    ["Mikasa", "Armin"],
    ["Zenitsu", "Inosuke"],
    ["Tanjiro", "Nezuko"],
    ["Uraraka", "Tsuyu"],
    ["Isekai", "School life"],
    ["Sports", "Battle shonen"],
    ["Romance", "Slice of life"],
    ["Horror", "Mystery"],
    ["Fantasy", "Sci-Fi"],
    ["Ghibli", "Makoto Shinkai"],
    ["MAPPA", "ufotable"],
  ],
};
export const LIAR_KEYWORDS_BY_LANG = {
  ko: LIAR_KEYWORDS,
  ja: LIAR_KEYWORDS_JA,
  en: LIAR_KEYWORDS_EN,
};

export function getLiarCategoriesByLang(lang) {
  return CATEGORIES_BY_LANG[lang] || CATEGORIES_BY_LANG.ko;
}
export function getLiarKeywordsByLang(lang) {
  const q = LIAR_KEYWORDS_BY_LANG[lang];
  if (!q) return LIAR_KEYWORDS_BY_LANG.ko;
  const merged = {};
  for (const catId of Object.keys(LIAR_KEYWORDS)) {
    const arr = q[catId];
    merged[catId] = (arr && arr.length > 0) ? arr : LIAR_KEYWORDS[catId];
  }
  return merged;
}
export function getLiarLangAvailability() {
  const out = {};
  for (const lang of Object.keys(LIAR_KEYWORDS_BY_LANG)) {
    const q = LIAR_KEYWORDS_BY_LANG[lang];
    let total = 0;
    for (const arr of Object.values(q)) total += (arr || []).length;
    out[lang] = total;
  }
  return out;
}

export function pickRandomPair(categoryId, lang = "ko") {
  const keywords = getLiarKeywordsByLang(lang);
  const list = keywords[categoryId] || [];
  if (!list.length) return null;
  const pair = list[Math.floor(Math.random() * list.length)];
  // 랜덤 셔플 — 어느 쪽이 시민 키워드인지도 랜덤
  if (Math.random() < 0.5) return [pair[0], pair[1]];
  return [pair[1], pair[0]];
}

export function totalPairsByCategory() {
  const out = {};
  for (const id of Object.keys(LIAR_KEYWORDS)) out[id] = LIAR_KEYWORDS[id].length;
  return out;
}
