// =========================
// DUO GAME ZONE / 인생게임
// 이벤트 데이터 — v20260514_1 (대형 확장: 성별/특수이벤트/로맨스/SNS/장기이벤트)
// =========================
//
// stage: infant(0~6) / child(7~12) / teen(13~18) / adult(19~30) / midlife(31~55) / "*"(longterm 결과)
// type: "normal" | "special" | "longterm" (longterm은 일반 풀에서 제외, longTerm 큐에서 강제 fire)
// genderRequired: 'M' | 'F' | ['M','F'] (옵셔널)
// flagRequired: ["elite_school"] (모두 충족)
// relationRequired: { romance: true } | { friendsMin: 1 }
// weight: 추첨 가중치 (기본 1, special 권장 0.6~1.0)
// effects: { money, happy, intel, social, power, internet, luck }
// route: 선택 시 획득/변경되는 인생 루트 플래그
// outcomes: 무작위 결과 배열 (chance 합계가 1이 아니어도 normalize)
// choice.relation: { romance?: name, friend?: name, delta?: N, breakup?: true, foe?: name }
// choice.flag:     { add?: [...], remove?: [...] }
// choice.longTerm: { resultEventId: "lt_...", after: 2 } — N턴 뒤 결과 이벤트 강제 fire
// =========================

export const STAGES = [
  { id: "infant",   label: "유아기",   emoji: "👶", ageStart: 0,  ageEnd: 6  },
  { id: "child",    label: "초등학생", emoji: "🧒", ageStart: 7,  ageEnd: 12 },
  { id: "teen",     label: "중고등",   emoji: "🧑", ageStart: 13, ageEnd: 18 },
  { id: "adult",    label: "성인",     emoji: "🎓", ageStart: 19, ageEnd: 30 },
  { id: "midlife",  label: "중년",     emoji: "👴", ageStart: 31, ageEnd: 55 },
];

// 각 stage에서 진행할 턴 수 (총 18턴)
// teen +1 (로맨스/진로 들어갈 자리), adult +1 (SNS/특수 이벤트 자리)
export const STAGE_TURNS = {
  infant: 2,
  child: 3,
  teen: 4,
  adult: 6,
  midlife: 3,
};

export const STAT_DEFS = [
  { key: "money",    label: "돈",       emoji: "💰", initial: 0,  isMoney: true },
  { key: "happy",    label: "행복",     emoji: "❤️", initial: 50 },
  { key: "intel",    label: "지능",     emoji: "🧠", initial: 50 },
  { key: "social",   label: "사회성",   emoji: "🤝", initial: 50 },
  { key: "power",    label: "체력",     emoji: "💪", initial: 60 },
  { key: "internet", label: "인터넷력", emoji: "🌐", initial: 30 },
  { key: "luck",     label: "운",       emoji: "🍀", initial: 50 },
];

export const ROUTES = {
  streamer: { label: "스트리머",   emoji: "🎥" },
  idol:     { label: "아이돌",     emoji: "🎤" },
  crypto:   { label: "코인러",     emoji: "📈" },
  politics: { label: "정치",       emoji: "🏛️" },
  ai:       { label: "AI 사업가",   emoji: "🧠" },
  athlete:  { label: "운동선수",   emoji: "💪" },
  gamer:    { label: "프로게이머", emoji: "🎮" },
  neet:     { label: "백수",       emoji: "💤" },
  worker:   { label: "직장인",     emoji: "💼" },
  student:  { label: "공부벌레",   emoji: "📚" },
  criminal: { label: "범죄자",     emoji: "🦹" },
  alien:    { label: "외계인 친구",emoji: "👽" },
  // ===== v20260514_1 신규 =====
  artist:    { label: "예술가",     emoji: "🎨" },
  parent:    { label: "엄빠",       emoji: "👶" },
  corporate: { label: "대기업",     emoji: "🏢" },
  traveler:  { label: "여행자",     emoji: "🏝️" },
  influencer:{ label: "인플루언서", emoji: "📱" },
};

export const EVENTS = [
  // ============================================================
  // INFANT (유아기)
  // ============================================================
  {
    id: "infant_first_word",
    stage: "infant",
    emoji: "👶",
    title: "첫마디",
    desc: "아기 입에서 처음으로 말이 튀어나오려는 순간! 첫마디는?",
    choices: [
      { id: "mom", emoji: "👩", text: "엄마", sub: "왕도 패턴", grade: "good",
        effects: { happy: +6, social: +4 },
        narratives: ["부모님이 SNS에 올려서 좋아요 200개를 받았다.", "할머니가 1시간 동안 우셨다."] },
      { id: "money", emoji: "💸", text: "돈", sub: "어딘가 어른 같은", grade: "crit",
        effects: { money: +20, happy: +2, luck: +3 },
        outcomes: [
          { chance: 0.3, effects: { money: +30, luck: +5 }, narrative: "할머니가 충격받아 통장 하나를 만들어주셨다." },
          { chance: 0.7, effects: {}, narrative: "할머니가 깜짝 놀라 용돈을 쥐어주셨다." },
        ] },
      { id: "wifi", emoji: "📶", text: "와이파이", sub: "디지털 네이티브", grade: "mid",
        effects: { internet: +12, intel: -3 },
        narratives: ["부모님이 통신사를 의심하기 시작했다."] },
      { id: "cuss", emoji: "🤬", text: "(욕설)", sub: "어디서 들었지?", grade: "bad",
        effects: { social: -8, happy: +3 },
        narratives: ["아빠가 식은땀을 흘렸다."] },
      { id: "scream", emoji: "📣", text: "...!!!", sub: "그냥 비명", grade: "bad",
        effects: { happy: -2, power: +5 },
        narratives: ["성대가 무지하게 발달했다."] },
    ],
  },
  {
    id: "infant_toy",
    stage: "infant",
    emoji: "🧸",
    title: "처음 잡은 장난감",
    desc: "어떤 장난감에 손이 갔을까?",
    choices: [
      { id: "book", emoji: "📚", text: "책", grade: "good",
        effects: { intel: +8, happy: -1 },
        narratives: ["그림책을 잘근잘근 씹었다. 영양분처럼 흡수했다."] },
      { id: "pad", emoji: "📱", text: "태블릿", grade: "mid",
        effects: { internet: +10, intel: -3, happy: +3 },
        narratives: ["유튜브 알고리즘이 너를 알아보기 시작했다."] },
      { id: "ball", emoji: "⚽", text: "공", grade: "good",
        effects: { power: +6, social: +2 },
        narratives: ["방 안의 모든 것을 차고 다녔다."] },
      { id: "coin", emoji: "🪙", text: "동전", grade: "crit",
        effects: { money: +5, luck: +5 },
        outcomes: [
          { chance: 0.1, effects: { money: +50, luck: +10 }, narrative: "1948년 발행 기념주화였다. 가치 폭등." },
          { chance: 0.9, effects: {}, narrative: "부모님이 사라진 동전들을 의심하기 시작했다." },
        ] },
      { id: "sword", emoji: "⚔️", text: "장난감 칼", grade: "mid",
        effects: { power: +5, social: -2, happy: +3 },
        narratives: ["하루 종일 가구를 베었다."] },
    ],
  },
  {
    id: "infant_grandma_envelope",
    stage: "infant",
    emoji: "👵",
    title: "외할머니의 비밀 봉투",
    desc: "외할머니가 흰 봉투를 슥 건네신다",
    choices: [
      { id: "open", emoji: "💸", text: "냉큼 받아 흔든다", grade: "good",
        effects: { money: +30, happy: +5 },
        narratives: ["손주 사랑 인증샷이 4년간 카톡 프사를 차지했다."] },
      { id: "give_back", emoji: "🤝", text: "엄마한테 갖다 줌", grade: "good",
        effects: { social: +5, intel: +3, happy: +2 },
        narratives: ["엄마가 친척 단톡방에 자랑했다. 다음 명절 용돈이 두 배가 됐다."] },
      { id: "rip", emoji: "🤡", text: "찢는다", grade: "bad",
        effects: { money: -10, happy: -5, intel: -3 },
        narratives: ["수표였다. 30만원이 휴지가 됐다."] },
      { id: "eat", emoji: "🍽️", text: "삼킨다", grade: "crit",
        effects: { power: -3 },
        outcomes: [
          { chance: 0.7, effects: { happy: -8, money: -30 }, narrative: "응급실. 배에서 50만원이 발견됐다." },
          { chance: 0.3, effects: { luck: +8, money: +50 }, narrative: "유튜브에 떠서 채널이 생겼다. 영상료가 들어왔다." },
        ] },
    ],
  },
  {
    id: "infant_bath",
    stage: "infant",
    emoji: "🛁",
    title: "목욕 시간",
    desc: "물에 대한 첫 반응은?",
    choices: [
      { id: "swim", emoji: "🏊", text: "물장구!", grade: "good",
        effects: { power: +6, happy: +5 } },
      { id: "cry", emoji: "😭", text: "대성통곡", grade: "bad",
        effects: { happy: -4, social: -2 } },
      { id: "pee", emoji: "💦", text: "...실수", grade: "mid",
        effects: { happy: +2, social: -3 },
        narratives: ["엄마가 한참을 웃었다."] },
      { id: "sing", emoji: "🎤", text: "샤워하며 노래", grade: "good", route: "idol",
        effects: { happy: +5, social: +3 },
        narratives: ["욕실 울림으로 음정이 살았다. 감춰진 재능."] },
    ],
  },

  // ============================================================
  // CHILD (초등학생)
  // ============================================================
  {
    id: "child_school_first",
    stage: "child",
    emoji: "🎒",
    title: "학교 첫날",
    desc: "초등학교 입학! 첫 행동은?",
    choices: [
      { id: "study", emoji: "📚", text: "맨 앞자리 사수", grade: "good", route: "student",
        effects: { intel: +7, social: -2 },
        narratives: ["선생님 눈에 띄었다."] },
      { id: "friend", emoji: "🤝", text: "옆자리 친구한테 말걸기", grade: "good",
        effects: { social: +8, happy: +4 },
        narratives: ["베프가 생겼다."] },
      { id: "fight", emoji: "👊", text: "쉬는시간 결투 신청", grade: "mid",
        effects: { power: +6, social: -4, happy: -2 },
        outcomes: [
          { chance: 0.4, effects: { power: +5, social: +5 }, narrative: "이겼다. 명성을 얻었다." },
          { chance: 0.4, effects: { happy: -6, power: -3 }, narrative: "졌다. 코피가 났다." },
          { chance: 0.2, effects: { happy: -10, social: -8 }, narrative: "선생님이 양쪽 부모 호출. 인생 첫 학폭위." },
        ] },
      { id: "skip", emoji: "🚪", text: "몰래 도망치기", grade: "bad",
        effects: { happy: +5, social: -4, intel: -2 },
        narratives: ["놀이터에서 발견되어 끌려갔다."] },
    ],
  },
  {
    id: "child_bully",
    stage: "child",
    emoji: "👊",
    title: "교실 빌런 등장",
    desc: "체육시간에 한 명이 너의 신발을 숨겼다",
    choices: [
      { id: "fight_back", emoji: "🥊", text: "맞대응 — 한판 뜬다", grade: "crit",
        effects: { power: +5 },
        outcomes: [
          { chance: 0.4, effects: { power: +8, social: +6, happy: +6 }, narrative: "이겼다. 반의 영웅이 되었다." },
          { chance: 0.4, effects: { power: -5, happy: -8, social: -3 }, narrative: "졌다. 코피 + 부모 호출." },
          { chance: 0.2, effects: { intel: -3, happy: -4, social: -5 }, narrative: "둘 다 정학을 받았다." },
        ] },
      { id: "tell_teacher", emoji: "🧑‍🏫", text: "선생님께 이른다", grade: "good",
        effects: { intel: +3, social: -2 },
        narratives: ["고자질쟁이라는 별명이 붙었다. 그래도 신발은 찾았다."] },
      { id: "trap", emoji: "🪤", text: "두 배로 갚아준다 (덫 설치)", grade: "crit",
        effects: { intel: +5 },
        outcomes: [
          { chance: 0.5, effects: { social: +8, happy: +10, luck: +5 }, narrative: "성공. 그 친구가 너를 두려워하기 시작했다." },
          { chance: 0.5, effects: { social: -10, happy: -8, intel: -3 }, narrative: "역으로 당했다. 신발도 잃고 자존심도 잃었다." },
        ] },
      { id: "ignore", emoji: "🙈", text: "그냥 맨발로 집에 감", grade: "bad",
        effects: { happy: -5, social: -3, power: +2 } },
    ],
  },
  {
    id: "child_game_addict",
    stage: "child",
    emoji: "🎮",
    title: "게임 중독",
    desc: "PC방의 유혹. 어떻게 할래?",
    choices: [
      { id: "all_in", emoji: "🔥", text: "올인 — 새벽까지", grade: "mid", route: "gamer",
        effects: { internet: +15, intel: -3, power: -5, happy: +6 },
        narratives: ["랭크가 미친듯이 올랐다."] },
      { id: "balance", emoji: "⚖️", text: "딱 1시간만", grade: "good",
        effects: { internet: +5, happy: +3, intel: +1 },
        narratives: ["엄마가 칭찬했다."] },
      { id: "refuse", emoji: "🚫", text: "공부하러 감", grade: "good", route: "student",
        effects: { intel: +8, social: -2, happy: -3 } },
      { id: "buy_skin", emoji: "💳", text: "엄마 카드로 스킨 구매", grade: "crit",
        effects: { money: -30, happy: +10, internet: +6 },
        outcomes: [
          { chance: 0.3, effects: { happy: -20, social: -8, money: -15 }, narrative: "엄마한테 걸려서 사망 직전까지 갔다." },
          { chance: 0.5, effects: { internet: +6 }, narrative: "전설 등급을 뽑았다. 친구들이 부러워했다." },
          { chance: 0.2, effects: { happy: +15, internet: +12, luck: +8 }, narrative: "한정판 스킨 떡상. 계정값이 50만원이 됐다." },
        ] },
    ],
  },
  {
    id: "child_pocket_money",
    stage: "child",
    emoji: "💴",
    title: "용돈 받았다",
    desc: "5천원이 생겼다. 어디에 쓸까?",
    choices: [
      { id: "snack", emoji: "🍿", text: "간식 박살내기", grade: "mid",
        effects: { happy: +6, power: -2, money: -5 } },
      { id: "save", emoji: "🏦", text: "저금통 직행", grade: "good",
        effects: { money: +5, happy: -2, intel: +3 },
        narratives: ["미래의 자산가가 시작되었다."] },
      { id: "lottery", emoji: "🎰", text: "뽑기 도전", grade: "crit",
        effects: { money: -5 },
        outcomes: [
          { chance: 0.05, effects: { money: +120, happy: +18, luck: +12 }, narrative: "🌟 1등! 디럭스 한정판!" },
          { chance: 0.15, effects: { money: +20, happy: +8, luck: +5 }, narrative: "2등. 인생 첫 스릴." },
          { chance: 0.3, effects: { money: +5, happy: +3 }, narrative: "그럭저럭." },
          { chance: 0.5, effects: { happy: -8, luck: -3 }, narrative: "꽝이었다. 인생 첫 좌절." },
        ] },
      { id: "donate", emoji: "🐶", text: "유기견 단체에 기부", grade: "good",
        effects: { money: -5, happy: +8, social: +5, luck: +3 },
        narratives: ["이상하게 그 후로 좋은 일이 늘었다."] },
    ],
  },
  {
    id: "child_youtube_debut",
    stage: "child",
    emoji: "📹",
    title: "유튜브 데뷔",
    desc: "쿠킹 영상이 갑자기 추천 알고리즘에 떴다",
    choices: [
      { id: "shorts", emoji: "🎬", text: "쇼츠 따라 만들기", grade: "good", route: "streamer",
        effects: { internet: +12, social: +3, happy: +5 },
        outcomes: [
          { chance: 0.05, effects: { internet: +25, money: +60, happy: +15 }, narrative: "🌟 1000만뷰. 키즈 유튜버 데뷔." },
          { chance: 0.15, effects: { internet: +12, happy: +8 }, narrative: "조회수 10만! 첫 인터넷 스타 경험." },
          { chance: 0.8, effects: {}, narrative: "조회수 7회. 그래도 시작이 반이다." },
        ] },
      { id: "watch", emoji: "👀", text: "그냥 본방 사수", grade: "mid",
        effects: { internet: +6, intel: -1 } },
      { id: "ignore", emoji: "🙅", text: "관심 없음", grade: "good",
        effects: { intel: +3, internet: -1 } },
      { id: "scam", emoji: "🎁", text: "가짜 경품 댓글에 반응", grade: "bad",
        effects: { internet: +3 },
        outcomes: [
          { chance: 0.9, effects: { money: -10, happy: -5 }, narrative: "휴대폰 번호가 광고 회사에 팔렸다." },
          { chance: 0.1, effects: { money: +20 }, narrative: "운 좋게 진짜였다." },
        ] },
    ],
  },
  {
    id: "child_birthday_party",
    stage: "child",
    emoji: "🎂",
    title: "친구 생일파티",
    desc: "20명이 모인 곳. 무얼 할까?",
    choices: [
      { id: "perform", emoji: "🎤", text: "노래 1곡 라이브", grade: "crit",
        effects: { social: +5 },
        outcomes: [
          { chance: 0.3, effects: { social: +12, happy: +10 }, narrative: "20명이 박수쳤다. 인생 첫 무대 성공." },
          { chance: 0.7, effects: { happy: -8, social: -5 }, narrative: "음정이 나갔다. 영상이 단톡방을 돌고 있다." },
        ] },
      { id: "magician", emoji: "🎩", text: "마술쇼 시도", grade: "mid",
        effects: { intel: +3 },
        outcomes: [
          { chance: 0.5, effects: { social: +8, happy: +5 }, narrative: "성공. 한동안 마술사라 불렸다." },
          { chance: 0.5, effects: { happy: -3 }, narrative: "트릭이 들통났다." },
        ] },
      { id: "eat_only", emoji: "🍰", text: "케이크 3조각 박살", grade: "good",
        effects: { happy: +6, power: -2, social: +1 } },
      { id: "leave", emoji: "🚪", text: "조용히 퇴장", grade: "bad",
        effects: { happy: -3, social: -5 } },
    ],
  },

  // ============================================================
  // TEEN (중고등)
  // ============================================================
  {
    id: "teen_test",
    stage: "teen",
    emoji: "📝",
    title: "기말고사",
    desc: "벼락치기 vs 컨닝 vs 포기 vs 진짜공부",
    choices: [
      { id: "real", emoji: "📚", text: "진짜 공부", grade: "good", route: "student",
        effects: { intel: +12, happy: -4, power: -3 },
        narratives: ["전교 등수가 올랐다. 부모님이 처음으로 자랑하셨다."] },
      { id: "cram", emoji: "⚡", text: "벼락치기", grade: "mid",
        effects: { intel: +5, happy: -2 },
        outcomes: [
          { chance: 0.4, effects: { intel: +6 }, narrative: "기적적으로 잘 봤다." },
          { chance: 0.6, effects: { happy: -4 }, narrative: "역시 안 됐다." },
        ] },
      { id: "cheat", emoji: "🕵️", text: "컨닝 시도", grade: "crit",
        effects: { intel: -2 },
        outcomes: [
          { chance: 0.3, effects: { happy: -20, social: -8, intel: -5 }, narrative: "걸려서 0점 + 정학. 부모님이 학교에 호출당했다." },
          { chance: 0.5, effects: { intel: +4, happy: +3 }, narrative: "성공. 이상한 자신감이 생겼다." },
          { chance: 0.2, effects: { intel: +8, happy: +6, luck: +5 }, narrative: "옆자리 답이 우연히도 다 정답이었다. 평생의 행운." },
        ] },
      { id: "give_up", emoji: "💤", text: "포기하고 잠", grade: "bad", route: "neet",
        effects: { intel: -4, happy: +6, power: +4 },
        narratives: ["꿀잠을 잤다. 미래가 어두워졌다."] },
    ],
  },
  {
    id: "teen_first_love",
    stage: "teen",
    emoji: "💌",
    title: "첫사랑",
    desc: "옆반 그 친구가 신경쓰인다",
    choices: [
      { id: "confess", emoji: "❤️", text: "고백한다", grade: "good",
        effects: { happy: +2 },
        outcomes: [
          { chance: 0.4, effects: { happy: +18, social: +8, luck: +5 }, narrative: "성공! 첫 연애 시작!" },
          { chance: 0.5, effects: { happy: -12, social: -3 }, narrative: "차였다. 일주일간 침대 신세." },
          { chance: 0.1, effects: { happy: +5, social: -8 }, narrative: "그 친구 친구가 좋아한다고 했다. 삼각관계 시작." },
        ] },
      { id: "letter", emoji: "📝", text: "익명 편지", grade: "mid",
        effects: { intel: +3, happy: -1 },
        outcomes: [
          { chance: 0.5, effects: { happy: +6 }, narrative: "고이 간직했다고 한다." },
          { chance: 0.5, effects: { happy: -8, social: -5 }, narrative: "필체로 들켜서 학교 전체가 알게 됐다." },
        ] },
      { id: "stalk", emoji: "📱", text: "SNS 30분간 정찰", grade: "bad",
        effects: { internet: +5, happy: -3, social: -2 },
        narratives: ["좋아요를 잘못 눌렀다. 지옥이 시작됐다."] },
      { id: "ignore", emoji: "📚", text: "공부에 매진", grade: "good", route: "student",
        effects: { intel: +8, happy: -3 } },
    ],
  },
  {
    id: "teen_school_violence",
    stage: "teen",
    emoji: "📱",
    title: "단톡방 사건",
    desc: "동창들 단톡방에 너의 합성사진이 돌고 있다",
    choices: [
      { id: "report", emoji: "📞", text: "학폭위 신고", grade: "good",
        effects: { intel: +6, social: -4 },
        outcomes: [
          { chance: 0.6, effects: { social: +6, happy: +8 }, narrative: "가해자들이 처벌받았다." },
          { chance: 0.4, effects: { happy: -8, social: -8 }, narrative: "증거 부족으로 묻혔다. 너만 따돌림." },
        ] },
      { id: "counter", emoji: "💣", text: "더 자극적인 합성으로 반격", grade: "crit",
        effects: { internet: +6 },
        outcomes: [
          { chance: 0.4, effects: { internet: +12, social: +5, happy: +6 }, narrative: "역으로 박살냈다. 단톡방의 새 권력자." },
          { chance: 0.6, effects: { happy: -15, intel: -3, social: -10 }, narrative: "고소당했다. 가해자가 됐다." },
        ] },
      { id: "ignore_it", emoji: "🎧", text: "이어폰 꽂고 외면", grade: "mid",
        effects: { happy: -5, intel: +2 } },
      { id: "viral", emoji: "🌐", text: "내가 먼저 인스타에 올림", grade: "crit", route: "streamer",
        effects: { internet: +5 },
        outcomes: [
          { chance: 0.25, effects: { internet: +18, happy: +10, social: +5 }, narrative: "셀프 디스로 대박. 인플루언서 데뷔." },
          { chance: 0.75, effects: { happy: -15, social: -8 }, narrative: "더 큰 화제가 되어버렸다." },
        ] },
    ],
  },
  {
    id: "teen_idol_audition",
    stage: "teen",
    emoji: "🎤",
    title: "지나가던 캐스팅",
    desc: "길에서 명함을 받았다",
    choices: [
      { id: "audition", emoji: "🎤", text: "오디션 본다", grade: "crit", route: "idol",
        effects: { social: +6, intel: -3 },
        outcomes: [
          { chance: 0.05, effects: { happy: +20, social: +15, money: +50, internet: +10 }, narrative: "🌟 메인보컬 합격! 차세대 슈퍼스타." },
          { chance: 0.15, effects: { happy: +12, social: +10, money: +30 }, narrative: "합격! 연습생이 되었다." },
          { chance: 0.8, effects: { happy: -10, money: -10 }, narrative: "사기였다. 차비 + 프로필 촬영비만 날렸다." },
        ] },
      { id: "burn", emoji: "🔥", text: "명함을 찢는다", grade: "good",
        effects: { intel: +4 },
        narratives: ["현명한 선택이었다."] },
      { id: "tiktok", emoji: "📱", text: "틱톡으로 도전", grade: "mid", route: "streamer",
        effects: { internet: +10, social: +4 },
        outcomes: [
          { chance: 0.1, effects: { internet: +20, happy: +12, money: +25 }, narrative: "댄스 챌린지가 떡상했다." },
          { chance: 0.9, effects: { happy: -3 }, narrative: "조회수 3회. 그중 2개는 본인." },
        ] },
    ],
  },
  {
    id: "teen_part_time",
    stage: "teen",
    emoji: "🍔",
    title: "첫 알바",
    desc: "용돈이 부족하다",
    choices: [
      { id: "burger", emoji: "🍟", text: "패스트푸드", grade: "good",
        effects: { money: +20, power: +3, happy: -3, social: +3 } },
      { id: "stream", emoji: "📺", text: "방송 시작", grade: "crit", route: "streamer",
        effects: { internet: +10 },
        outcomes: [
          { chance: 0.05, effects: { money: +120, internet: +25, happy: +15 }, narrative: "데뷔 1주일만에 시청자 1000명. 화제." },
          { chance: 0.15, effects: { money: +30, internet: +10 }, narrative: "도네이션 약간 들어왔다." },
          { chance: 0.8, effects: { happy: -4, money: -5 }, narrative: "시청자 0명. 카메라 보고 혼잣말만 했다." },
        ] },
      { id: "stock", emoji: "📊", text: "용돈으로 주식", grade: "crit", route: "crypto",
        effects: { intel: +3 },
        outcomes: [
          { chance: 0.15, effects: { money: +60, intel: +5, luck: +5 }, narrative: "운이 좋았다. 첫 매수가 그대로 떡상." },
          { chance: 0.85, effects: { money: -25, happy: -6 }, narrative: "손절도 못 하고 물렸다." },
        ] },
      { id: "delivery", emoji: "🛵", text: "배달 알바", grade: "mid",
        effects: { money: +25, power: +5, intel: -2 },
        outcomes: [
          { chance: 0.1, effects: { money: -30, power: -10, happy: -8 }, narrative: "사고가 났다. 보험금만 빠져나갔다." },
          { chance: 0.9, effects: {}, narrative: "그럭저럭 벌었다." },
        ] },
    ],
  },
  {
    id: "teen_festival",
    stage: "teen",
    emoji: "🎪",
    title: "학교 축제 무대",
    desc: "댄스 무대 자원자 모집",
    choices: [
      { id: "go", emoji: "💃", text: "올라간다", grade: "crit",
        effects: { social: +3 },
        outcomes: [
          { chance: 0.25, effects: { social: +12, happy: +10, internet: +8 }, narrative: "영상이 학교 인스타에 떠서 추종자가 생겼다." },
          { chance: 0.5, effects: { happy: -3, social: +3 }, narrative: "무난했다. 그래도 박수 받음." },
          { chance: 0.25, effects: { happy: -10, social: -5 }, narrative: "넘어졌다. 영상이 학교에서 영원히 회자된다." },
        ] },
      { id: "stage_helper", emoji: "🔧", text: "무대 스태프 자원", grade: "good",
        effects: { intel: +5, social: +5, happy: +3 } },
      { id: "skip", emoji: "🚪", text: "도서관으로 도망", grade: "good", route: "student",
        effects: { intel: +6, happy: -2 } },
      { id: "explosion", emoji: "🎆", text: "폭죽 몰래 터뜨리기", grade: "crit",
        effects: { happy: +5 },
        outcomes: [
          { chance: 0.4, effects: { social: +8, happy: +10 }, narrative: "전설의 축제 영웅이 됐다." },
          { chance: 0.6, effects: { happy: -15, social: -10, money: -20 }, narrative: "정학 + 손해배상. 부모님 쇼크." },
        ] },
    ],
  },
  {
    id: "teen_insta_influence",
    stage: "teen",
    emoji: "📸",
    title: "인스타 시작",
    desc: "친구들이 다 한다. 너도?",
    choices: [
      { id: "go_hard", emoji: "🔥", text: "주 7회 업로드 풀가동", grade: "crit", route: "streamer",
        effects: { internet: +10, intel: -3 },
        outcomes: [
          { chance: 0.2, effects: { internet: +20, social: +10, money: +25 }, narrative: "1만 팔로워 달성. 협찬이 들어왔다." },
          { chance: 0.8, effects: { happy: -3 }, narrative: "팔로워 47명. 알고리즘이 외면했다." },
        ] },
      { id: "lurk", emoji: "👀", text: "구경만", grade: "mid",
        effects: { internet: +3, happy: -2 } },
      { id: "no", emoji: "🚫", text: "SNS 안 함", grade: "good",
        effects: { intel: +5, happy: +5, internet: -3 } },
    ],
  },

  // ============================================================
  // ADULT (성인)
  // ============================================================
  {
    id: "adult_uni",
    stage: "adult",
    emoji: "🎓",
    title: "수능 결과",
    desc: "결과가 나왔다",
    choices: [
      { id: "sky", emoji: "🏛️", text: "명문대 지원", grade: "good", route: "student",
        statRequired: { intel: 60 },
        effects: { intel: +6, happy: +8, social: +5 },
        outcomes: [
          { chance: 0.5, effects: { intel: +5, social: +3 }, narrative: "합격! 미래가 밝아졌다." },
          { chance: 0.5, effects: { happy: -8 }, narrative: "재수가 시작됐다." },
        ] },
      { id: "normal", emoji: "📖", text: "지방대", grade: "mid",
        effects: { intel: +3, happy: +2, social: +2 },
        narratives: ["편한 학교생활이 시작됐다."] },
      { id: "skip_uni", emoji: "🚀", text: "대학 안 감 (사업/방송)", grade: "crit",
        effects: { internet: +5, intel: -3, happy: +6 },
        narratives: ["부모님이 일주일간 잠을 못 주무셨다."] },
      { id: "abroad", emoji: "✈️", text: "해외 유학", grade: "crit",
        effects: { money: -100 },
        outcomes: [
          { chance: 0.3, effects: { intel: +12, social: +10, money: +50, happy: +8 }, narrative: "성공. 외국인 친구도 많이 사귀었다." },
          { chance: 0.7, effects: { happy: -10, money: -50 }, narrative: "외로움 + 학비 폭탄." },
        ] },
      { id: "army_first", emoji: "🪖", text: "바로 군대", grade: "mid",
        effects: { power: +12, social: +5, happy: -8, intel: -3 } },
    ],
  },
  {
    id: "adult_army",
    stage: "adult",
    emoji: "🪖",
    title: "입영 통지서",
    desc: "그 갈색 봉투가 도착했다",
    choices: [
      { id: "active", emoji: "🪖", text: "현역으로 간다", grade: "good",
        effects: { power: +15, social: +5, happy: -10, intel: -3 },
        outcomes: [
          { chance: 0.1, effects: { power: +10, happy: +5, money: +30 }, narrative: "특수부대. 평생 자랑거리 + 보너스." },
          { chance: 0.9, effects: {}, narrative: "전역 후 '리얼 군대썰'로 모든 모임을 평정했다." },
        ] },
      { id: "social_service", emoji: "🏢", text: "사회복무요원", grade: "mid",
        effects: { power: +3, happy: +5, social: +3, intel: +2 } },
      { id: "art_olympic", emoji: "🎺", text: "예체능 특기 면제 도전", grade: "crit",
        effects: { intel: +3 },
        outcomes: [
          { chance: 0.05, effects: { happy: +20, money: +50 }, narrative: "🌟 면제. 인생 한 번 더 사는 느낌." },
          { chance: 0.95, effects: { happy: -10 }, narrative: "탈락. 결국 입대." },
        ] },
      { id: "fake", emoji: "🦴", text: "병원 다니며 면제 노림", grade: "crit",
        effects: { intel: -3 },
        outcomes: [
          { chance: 0.1, effects: { happy: +15, power: -5 }, narrative: "면제 성공. 평생 가짜 발목으로 산다." },
          { chance: 0.4, effects: { happy: -8 }, narrative: "결국 그냥 입대." },
          { chance: 0.5, effects: { happy: -25, social: -15, money: -50, intel: -5 }, narrative: "병역기피로 적발. 인스타에 박제됐다.", route: "criminal" },
        ] },
    ],
  },
  {
    id: "adult_first_job",
    stage: "adult",
    emoji: "💼",
    title: "첫 취업",
    desc: "어디로 갈까?",
    choices: [
      { id: "samsung", emoji: "🏢", text: "대기업", grade: "good", route: "worker",
        statRequired: { intel: 65 },
        effects: { money: +60, happy: -5, power: -8, social: +3 },
        narratives: ["연봉은 좋은데 야근이 시작됐다."] },
      { id: "startup", emoji: "🚀", text: "스타트업", grade: "crit", route: "ai",
        effects: { intel: +5, happy: +3 },
        outcomes: [
          { chance: 0.05, effects: { money: +500, intel: +12, happy: +15 }, narrative: "🌟 IPO. 스톡옵션이 폭발했다. 30대 부자." },
          { chance: 0.15, effects: { money: +120, intel: +8, happy: +6 }, narrative: "스톡옵션이 터졌다." },
          { chance: 0.8, effects: { money: +20, happy: -8, power: -10 }, narrative: "회사가 망했다." },
        ] },
      { id: "freelance", emoji: "🎨", text: "프리랜서", grade: "mid",
        effects: { money: +25, happy: +4, social: -3 } },
      { id: "neet", emoji: "🛏️", text: "취업 포기 (백수)", grade: "bad", route: "neet",
        effects: { happy: +12, money: -10, social: -8 },
        narratives: ["부모님 한숨이 깊어졌다."] },
      { id: "stream_full", emoji: "📺", text: "전업 스트리머", grade: "crit", route: "streamer",
        effects: { internet: +12, money: -15 },
        outcomes: [
          { chance: 0.05, effects: { money: +500, internet: +30, happy: +20 }, narrative: "🌟 구독자 100만. 광고 + 합방 + 굿즈로 매월 2억." },
          { chance: 0.15, effects: { money: +200, internet: +20, happy: +15 }, narrative: "구독자 10만 돌파!" },
          { chance: 0.8, effects: { money: -10, happy: -8 }, narrative: "동접 0명이 6개월간 지속됐다." },
        ] },
    ],
  },
  {
    id: "adult_crypto_yolo",
    stage: "adult",
    emoji: "🪙",
    title: "코인 떡상",
    desc: "친구가 '인생 마지막 기회'라며 코인을 추천했다",
    choices: [
      { id: "all_in", emoji: "🔥", text: "전재산 올인", grade: "crit", route: "crypto",
        effects: { intel: -3 },
        outcomes: [
          { chance: 0.05, effects: { money: +1500, happy: +30, luck: +15 }, narrative: "🌟 100배 떡상. 평생 일 안 해도 됨." },
          { chance: 0.1, effects: { money: +400, happy: +20, luck: +10 }, narrative: "10배 떡상! 조기 은퇴 가능?!" },
          { chance: 0.25, effects: { money: +80, happy: +6 }, narrative: "약간의 수익. 손 떨면서 익절했다." },
          { chance: 0.6, effects: { money: -100, happy: -25, intel: +3 }, narrative: "반토막. 이불 속에서 비명을 질렀다." },
        ] },
      { id: "small", emoji: "📊", text: "10%만 투자", grade: "mid",
        effects: { intel: +3 },
        outcomes: [
          { chance: 0.3, effects: { money: +30 }, narrative: "안전한 수익." },
          { chance: 0.7, effects: { money: -8 }, narrative: "소소한 손실." },
        ] },
      { id: "short", emoji: "📉", text: "오히려 숏 친다", grade: "crit",
        effects: { intel: +5 },
        outcomes: [
          { chance: 0.3, effects: { money: +200, happy: +10 }, narrative: "정확히 고점. 천재가 됐다." },
          { chance: 0.7, effects: { money: -150, happy: -20 }, narrative: "숏 청산. 자취방 보증금까지 사라짐." },
        ] },
      { id: "refuse", emoji: "🛡️", text: "거절", grade: "good",
        effects: { intel: +5, money: +5 },
        narratives: ["친구는 그 후 사라졌다."] },
    ],
  },
  {
    id: "adult_pyramid",
    stage: "adult",
    emoji: "🔺",
    title: "다단계 권유",
    desc: "고향 친구가 \"인생 한 번 뒤집을 기회\"라며 카페에서 만나자고 한다",
    choices: [
      { id: "join", emoji: "💼", text: "들어간다", grade: "crit",
        effects: { social: +3, intel: -5 },
        outcomes: [
          { chance: 0.05, effects: { money: +250, social: +10 }, narrative: "초기 멤버였다. 진짜 돈을 벌었다." },
          { chance: 0.15, effects: { money: -30, social: -5 }, narrative: "약간 손해보고 빠져나옴." },
          { chance: 0.8, effects: { money: -100, happy: -20, social: -15 }, narrative: "친구도 잃고 돈도 잃었다." },
        ] },
      { id: "report", emoji: "📞", text: "신고한다", grade: "good",
        effects: { intel: +6, social: +3, money: +10 },
        narratives: ["신고 포상금이 들어왔다."] },
      { id: "infiltrate", emoji: "🕵️", text: "위장 잠입 — 내부고발 노림", grade: "crit",
        effects: { intel: +5 },
        outcomes: [
          { chance: 0.3, effects: { money: +80, happy: +15, social: +6 }, narrative: "MBC PD수첩에 출연. 영웅이 됐다." },
          { chance: 0.7, effects: { money: -50, happy: -10 }, narrative: "본인이 너무 깊이 빠져버림." },
        ] },
      { id: "run", emoji: "🏃", text: "도망간다", grade: "good",
        effects: { intel: +3, social: -3 } },
    ],
  },
  {
    id: "adult_dating",
    stage: "adult",
    emoji: "💕",
    title: "소개팅",
    desc: "지인이 소개팅을 잡아줬다",
    choices: [
      { id: "go", emoji: "👔", text: "갈끔하게 차려입고 출동", grade: "good",
        effects: { happy: +3, money: -8 },
        outcomes: [
          { chance: 0.1, effects: { happy: +20, social: +12, luck: +6 }, narrative: "🌟 한눈에 반함. 1년 후 결혼 직행." },
          { chance: 0.4, effects: { happy: +12, social: +6 }, narrative: "잘 됐다. 애프터까지." },
          { chance: 0.5, effects: { happy: -4 }, narrative: "어색했다. 무사히 끝났다." },
        ] },
      { id: "skip", emoji: "🛏️", text: "거절. 그냥 잠", grade: "mid", route: "neet",
        effects: { happy: +5, social: -4 } },
      { id: "stream_it", emoji: "📹", text: "몰래 방송하면서 감", grade: "crit", route: "streamer",
        effects: { internet: +5 },
        outcomes: [
          { chance: 0.1, effects: { internet: +18, money: +40 }, narrative: "방송 떡상. 사람은 잃었지만 구독자를 얻었다." },
          { chance: 0.9, effects: { happy: -18, social: -12 }, narrative: "걸렸다. 차였다. 인생도 망쳤다." },
        ] },
      { id: "honesty", emoji: "🧠", text: "첫만남에 본 모습 100%", grade: "crit",
        effects: { intel: +3 },
        outcomes: [
          { chance: 0.3, effects: { happy: +12, social: +8 }, narrative: "오히려 진심이 통했다." },
          { chance: 0.7, effects: { happy: -5, social: -3 }, narrative: "차였다. 진심은 위험했다." },
        ] },
    ],
  },
  {
    id: "adult_marriage",
    stage: "adult",
    emoji: "💍",
    title: "결혼 압박",
    desc: "부모님이 명절마다 묻는다",
    choices: [
      { id: "marry", emoji: "💒", text: "결혼한다", grade: "good",
        effects: { money: -80, happy: +18, social: +6 },
        narratives: ["통장이 텅장이 됐지만 행복하다."] },
      { id: "single", emoji: "🕊️", text: "비혼 선언", grade: "mid",
        effects: { happy: +8, money: +30, social: -4 } },
      { id: "delay", emoji: "🤐", text: "그냥 도망", grade: "bad",
        effects: { happy: -3, social: -3 },
        narratives: ["다음 명절에도 같은 질문을 받는다."] },
      { id: "fake_marry", emoji: "💸", text: "위장결혼 제안 받음", grade: "crit",
        effects: { intel: -3 },
        outcomes: [
          { chance: 0.4, effects: { money: +120, happy: -5 }, narrative: "거액 챙기고 깔끔히 정리." },
          { chance: 0.6, effects: { money: -80, happy: -15, social: -10 }, narrative: "사기당했다. 빚만 떠안음.", route: "criminal" },
        ] },
    ],
  },
  {
    id: "adult_political",
    stage: "adult",
    emoji: "🏛️",
    title: "정치 입문 권유",
    desc: "동네 선배가 출마를 권한다",
    choices: [
      { id: "run", emoji: "🗳️", text: "출마한다", grade: "crit", route: "politics",
        statRequired: { social: 60 },
        effects: { money: -50, social: +6 },
        outcomes: [
          { chance: 0.1, effects: { money: +250, social: +20, happy: +12, luck: +5 }, narrative: "🌟 압도적 당선. 차세대 리더로 주목." },
          { chance: 0.2, effects: { money: +100, social: +12, happy: +8 }, narrative: "당선! 정치인이 되었다." },
          { chance: 0.7, effects: { money: -80, happy: -15 }, narrative: "낙선. 빚만 남았다." },
        ] },
      { id: "advise", emoji: "📢", text: "참모/보좌관", grade: "mid", route: "politics",
        effects: { intel: +6, social: +5, money: +20 } },
      { id: "scandal", emoji: "🎤", text: "라이벌 스캔들 폭로", grade: "crit",
        effects: { intel: +5 },
        outcomes: [
          { chance: 0.4, effects: { money: +50, social: +10 }, narrative: "정치판에 강자로 떠올랐다." },
          { chance: 0.6, effects: { money: -100, happy: -15, social: -15 }, narrative: "역공받았다. 너의 과거가 더 털렸다." },
        ] },
      { id: "no", emoji: "🚫", text: "정치는 노노", grade: "good",
        effects: { happy: +5 } },
    ],
  },
  {
    id: "adult_ai_business",
    stage: "adult",
    emoji: "🤖",
    title: "AI 붐",
    desc: "AI로 뭘 해볼까?",
    choices: [
      { id: "wrapper", emoji: "🧠", text: "AI 래퍼 서비스 창업", grade: "crit", route: "ai",
        effects: { intel: +5, money: -20 },
        outcomes: [
          { chance: 0.05, effects: { money: +1500, intel: +20, happy: +20 }, narrative: "🌟 인수합병 1000억. 투자자가 줄을 섰다." },
          { chance: 0.2, effects: { money: +250, intel: +10 }, narrative: "월 매출 1억 돌파!" },
          { chance: 0.75, effects: { money: -30, happy: -6 }, narrative: "사용자가 안 모인다." },
        ] },
      { id: "use", emoji: "✍️", text: "업무에 AI 활용만", grade: "good",
        effects: { intel: +6, money: +12, happy: +3 } },
      { id: "deepfake", emoji: "🎭", text: "딥페이크로 한 탕?", grade: "crit",
        effects: { intel: +3 },
        outcomes: [
          { chance: 0.2, effects: { money: +200, internet: +10 }, narrative: "익명 계정으로 짭짤하게." },
          { chance: 0.8, effects: { money: -30, happy: -25, social: -20 }, narrative: "추적당해 형사처벌. 인생 끝.", route: "criminal" },
        ] },
      { id: "fear", emoji: "😨", text: "AI 무서워 회피", grade: "bad",
        effects: { intel: -3, internet: -5 } },
    ],
  },
  {
    id: "adult_dinner_party",
    stage: "adult",
    emoji: "🍻",
    title: "회식 폭탄",
    desc: "부장이 \"오늘은 너만 믿는다\" 하며 잔을 들이댄다",
    routeRequired: ["worker"],
    choices: [
      { id: "drink_all", emoji: "🍶", text: "전부 받아 마신다", grade: "crit",
        effects: { social: +5, power: -8 },
        outcomes: [
          { chance: 0.4, effects: { social: +10, money: +20 }, narrative: "부장의 이쁨을 받았다. 다음달 보너스 추가." },
          { chance: 0.6, effects: { happy: -10, power: -8 }, narrative: "필름이 끊겼다. 다음날 인사이동 통보를 받았다." },
        ] },
      { id: "speak_up", emoji: "🎤", text: "솔직하게 한 마디", grade: "crit",
        effects: { intel: +3 },
        outcomes: [
          { chance: 0.3, effects: { happy: +15, social: +10 }, narrative: "부장이 \"멋지다\" 인정. 의외의 친목." },
          { chance: 0.7, effects: { social: -12, money: -15, happy: -8 }, narrative: "다음 인사고과 D 받았다." },
        ] },
      { id: "fake_sick", emoji: "🤢", text: "화장실에서 1시간 죽치기", grade: "mid",
        effects: { social: -3, happy: +3 } },
      { id: "leave_early", emoji: "🚪", text: "갑자기 \"애 아파요\"", grade: "good",
        effects: { intel: +3, happy: +5, social: -2 } },
    ],
  },
  {
    id: "adult_inheritance",
    stage: "adult",
    emoji: "📜",
    title: "갑작스런 유산",
    desc: "본 적 없는 큰아버지가 너를 유일한 상속인으로 지정했다는 연락",
    choices: [
      { id: "go_get", emoji: "🏃", text: "당장 변호사 사무실로", grade: "crit",
        effects: { intel: +3 },
        outcomes: [
          { chance: 0.05, effects: { money: +1200, happy: +25, luck: +20 }, narrative: "🌟 강남 빌딩 한 채. 일 안 해도 평생 돈 들어옴." },
          { chance: 0.2, effects: { money: +500, happy: +20, luck: +10 }, narrative: "건물 1채. 임대료가 매달 들어온다." },
          { chance: 0.4, effects: { money: +50, happy: +5 }, narrative: "예금 약간. 그래도 공돈." },
          { chance: 0.35, effects: { money: -30, happy: -8 }, narrative: "유산이 아니라 빚이었다. 한정승인 변호사비만 깨졌다." },
        ] },
      { id: "give_up", emoji: "🚫", text: "포기한다", grade: "good",
        effects: { intel: +3, happy: +2 } },
      { id: "scam_check", emoji: "📵", text: "보이스피싱이라 의심", grade: "good",
        effects: { intel: +6 },
        outcomes: [
          { chance: 0.7, effects: { happy: +5 }, narrative: "현명했다. 보이스피싱 맞았다." },
          { chance: 0.3, effects: { happy: -15 }, narrative: "진짜 유산이었는데 시효가 끝났다." },
        ] },
    ],
  },
  {
    id: "adult_jeonse_scam",
    stage: "adult",
    emoji: "🏚️",
    title: "전세 계약",
    desc: "예산보다 훨씬 좋은 매물을 찾았다",
    choices: [
      { id: "rush", emoji: "✍️", text: "바로 계약", grade: "crit",
        effects: { money: -30 },
        outcomes: [
          { chance: 0.4, effects: { happy: +6 }, narrative: "안전했다. 잘 살았다." },
          { chance: 0.6, effects: { money: -150, happy: -25, intel: +5, social: -3 }, narrative: "전세사기. 보증금 사라졌다." },
        ] },
      { id: "check", emoji: "🔍", text: "등기부등본 30번 검토", grade: "good",
        effects: { intel: +6, happy: +3, money: -10 } },
      { id: "monthly", emoji: "🔑", text: "월세로 안전 가기", grade: "good",
        effects: { intel: +3, money: -5 } },
      { id: "hostel", emoji: "🏠", text: "차라리 부모님 집", grade: "mid", route: "neet",
        effects: { money: +30, happy: -5, social: -3 } },
    ],
  },
  {
    id: "adult_loan_friend",
    stage: "adult",
    emoji: "🤝",
    title: "친구의 빚보증",
    desc: "오랜 친구가 \"형제 같은 너만 믿는다\"며 보증을 부탁",
    choices: [
      { id: "sign", emoji: "✍️", text: "사인한다", grade: "crit",
        outcomes: [
          { chance: 0.3, effects: { social: +6, happy: +5 }, narrative: "친구가 잘 갚았다. 우정이 깊어졌다." },
          { chance: 0.7, effects: { money: -200, happy: -25, social: -15 }, narrative: "친구가 도망갔다. 빚이 너에게 왔다." },
        ] },
      { id: "no", emoji: "🚫", text: "단호히 거절", grade: "good",
        effects: { intel: +5, social: -5 } },
      { id: "give_money", emoji: "💸", text: "차라리 일부 그냥 줌", grade: "mid",
        effects: { money: -20, happy: +3, social: +3 } },
    ],
  },
  {
    id: "adult_meme_viral",
    stage: "adult",
    emoji: "🤣",
    title: "내가 밈이 됐다",
    desc: "회사 회식 짤이 인터넷에 박제됐다",
    choices: [
      { id: "ride", emoji: "🏄", text: "셀프 패러디로 라이딩", grade: "crit", route: "streamer",
        effects: { internet: +12 },
        outcomes: [
          { chance: 0.4, effects: { internet: +20, money: +80, happy: +12 }, narrative: "광고 제안 폭주. 짤테크 성공." },
          { chance: 0.6, effects: { happy: -5 }, narrative: "잠깐 화제 후 잊혔다." },
        ] },
      { id: "lawsuit", emoji: "⚖️", text: "법적 대응", grade: "mid",
        effects: { money: -15, happy: -5 },
        outcomes: [
          { chance: 0.5, effects: { money: +50, social: +5 }, narrative: "위자료 받아냈다." },
          { chance: 0.5, effects: { money: -10 }, narrative: "기각. 변호사비만 까먹음." },
        ] },
      { id: "hide", emoji: "🫥", text: "잠수 + SNS 폭파", grade: "bad",
        effects: { happy: -8, internet: -10, social: -5 } },
    ],
  },
  {
    id: "adult_drunk_drive",
    stage: "adult",
    emoji: "🚗",
    title: "음주운전 유혹",
    desc: "회식 후 \"근거리니까 괜찮겠지\"",
    choices: [
      { id: "drive", emoji: "🚘", text: "운전한다", grade: "crit",
        outcomes: [
          { chance: 0.4, effects: { happy: +2 }, narrative: "운 좋게 안 걸렸다. 하지만 매번 운이 좋을까?" },
          { chance: 0.4, effects: { money: -100, happy: -25, social: -15, intel: -3 }, narrative: "단속 + 면허 취소 + 회사 통보." },
          { chance: 0.2, effects: { money: -300, happy: -30, social: -25, power: -15 }, narrative: "사고. 인명 피해. 인생이 끝났다.", route: "criminal" },
        ] },
      { id: "taxi", emoji: "🚕", text: "택시 호출", grade: "good",
        effects: { money: -8, intel: +5, happy: +3 } },
      { id: "代駕", emoji: "🤝", text: "대리기사 부름", grade: "good",
        effects: { money: -5, intel: +5 } },
    ],
  },
  {
    id: "adult_workout",
    stage: "adult",
    emoji: "💪",
    title: "PT 등록",
    desc: "헬스장에 큰 돈을 썼다",
    choices: [
      { id: "go", emoji: "🏋️", text: "꾸준히 다닌다", grade: "good",
        effects: { money: -20, power: +18, happy: +6 },
        narratives: ["몸이 변했다. 자신감도 변했다."] },
      { id: "ghost", emoji: "🛏️", text: "3일 가고 안 감", grade: "bad",
        effects: { money: -20, power: -2, happy: -4 } },
      { id: "athlete", emoji: "🥇", text: "아예 운동선수 도전", grade: "crit", route: "athlete",
        effects: { power: +8 },
        outcomes: [
          { chance: 0.05, effects: { power: +25, money: +500, social: +15 }, narrative: "🌟 국가대표 + 광고모델." },
          { chance: 0.15, effects: { power: +20, money: +120, social: +10 }, narrative: "프로팀 입단!" },
          { chance: 0.8, effects: { happy: -8, money: -15 }, narrative: "현실의 벽을 느꼈다." },
        ] },
      { id: "steroid", emoji: "💊", text: "스테로이드 도전", grade: "crit",
        effects: { power: +12 },
        outcomes: [
          { chance: 0.3, effects: { power: +20, social: +5 }, narrative: "몸이 미친듯이 변했다. SNS 인플루언서급." },
          { chance: 0.7, effects: { power: -15, happy: -15, money: -50 }, narrative: "부작용. 입원 + 평생 약값." },
        ] },
    ],
  },
  {
    id: "adult_burnout",
    stage: "adult",
    emoji: "🔥",
    title: "번아웃",
    desc: "회사가 너무 힘들다",
    routeRequired: ["worker"],
    choices: [
      { id: "quit", emoji: "✋", text: "퇴사한다", grade: "mid", route: "neet",
        effects: { money: -40, happy: +18, power: +6 },
        narratives: ["통장은 줄었지만 마음은 가벼워졌다."] },
      { id: "endure", emoji: "🦾", text: "버틴다", grade: "bad",
        effects: { money: +40, happy: -15, power: -10 } },
      { id: "transfer", emoji: "🔄", text: "이직 준비", grade: "good",
        effects: { intel: +5, money: -5, happy: +3 },
        outcomes: [
          { chance: 0.5, effects: { money: +60, happy: +10 }, narrative: "성공. 연봉도 올랐다." },
          { chance: 0.5, effects: { money: -10, happy: -4 }, narrative: "다 떨어졌다." },
        ] },
      { id: "fmla", emoji: "🌴", text: "병가 + 1달 잠수", grade: "crit",
        effects: { happy: +12, power: +6 },
        outcomes: [
          { chance: 0.4, effects: { happy: +6 }, narrative: "복귀. 멀쩡해졌다." },
          { chance: 0.6, effects: { money: -30, happy: -8 }, narrative: "잘렸다." },
        ] },
    ],
  },

  // ============================================================
  // MIDLIFE (중년)
  // ============================================================
  {
    id: "midlife_house",
    stage: "midlife",
    emoji: "🏠",
    title: "집을 살까?",
    desc: "월세에서 벗어나고 싶다",
    choices: [
      { id: "loan", emoji: "🏦", text: "영끌 대출", grade: "crit",
        effects: { money: -80 },
        outcomes: [
          { chance: 0.05, effects: { money: +600, happy: +18, luck: +10 }, narrative: "🌟 그 동네가 강남2급으로 떠오름. 5억 차익." },
          { chance: 0.45, effects: { money: +120, happy: +6 }, narrative: "집값이 올랐다. 영끌 성공." },
          { chance: 0.5, effects: { money: -100, happy: -15 }, narrative: "하락기. 이자 폭탄." },
        ] },
      { id: "rent", emoji: "🔑", text: "계속 월세", grade: "good",
        effects: { money: +20, happy: -3 } },
      { id: "country", emoji: "🌾", text: "시골 이주", grade: "mid",
        effects: { money: +30, happy: +12, social: -8, internet: -10 },
        narratives: ["인터넷이 100kbps라는 사실은 나중에 알았다."] },
      { id: "ghost_house", emoji: "👻", text: "흉가 매물 — 반값에", grade: "crit",
        effects: { money: -20, intel: -3 },
        outcomes: [
          { chance: 0.1, effects: { money: +200, happy: +5 }, narrative: "리모델링 후 시세 회복. 뜻밖의 노다지." },
          { chance: 0.9, effects: { happy: -15, power: -5 }, narrative: "진짜 귀신이 나왔다. 잠을 못 잔다." },
        ] },
    ],
  },
  {
    id: "midlife_kids",
    stage: "midlife",
    emoji: "👶",
    title: "육아 vs 워라밸",
    desc: "아이가 생겼거나 생기려 한다",
    choices: [
      { id: "kid", emoji: "👨‍👩‍👧", text: "육아 풀가동", grade: "good",
        effects: { money: -60, happy: +14, power: -8, social: +3 } },
      { id: "dual", emoji: "💼", text: "맞벌이 + 어린이집", grade: "mid",
        effects: { money: +20, happy: -3, power: -5 } },
      { id: "no", emoji: "🐾", text: "안 낳고 강아지", grade: "good",
        effects: { happy: +12, money: -10 } },
      { id: "twins", emoji: "👯", text: "쌍둥이가 나왔다", grade: "crit",
        outcomes: [
          { chance: 0.5, effects: { money: -100, happy: +20, power: -15 }, narrative: "행복하지만 파산 직전." },
          { chance: 0.5, effects: { money: -120, happy: +5, power: -20 }, narrative: "지옥의 4년이 시작됐다." },
        ] },
    ],
  },
  {
    id: "midlife_kids_teen",
    stage: "midlife",
    emoji: "🤬",
    title: "자녀 사춘기",
    desc: "방문이 잠겼다. 노크하니 \"신경 끄세요\"",
    choices: [
      { id: "talk", emoji: "💬", text: "조곤조곤 대화 시도", grade: "good",
        effects: { intel: +5, social: +3 },
        outcomes: [
          { chance: 0.5, effects: { happy: +6 }, narrative: "통했다. 같이 라면을 끓였다." },
          { chance: 0.5, effects: { happy: -3 }, narrative: "더 깊이 잠겼다." },
        ] },
      { id: "yell", emoji: "📢", text: "소리지른다", grade: "bad",
        effects: { happy: -8, social: -5, power: -3 } },
      { id: "leave_alone", emoji: "🚪", text: "그냥 둔다", grade: "mid",
        effects: { happy: -2, intel: +3 } },
      { id: "bribe", emoji: "💸", text: "용돈으로 회유", grade: "mid",
        effects: { money: -15, happy: +3, social: +2 } },
    ],
  },
  {
    id: "midlife_health",
    stage: "midlife",
    emoji: "🩺",
    title: "건강검진",
    desc: "결과지를 받았다",
    choices: [
      { id: "diet", emoji: "🥗", text: "다이어트 시작", grade: "good",
        effects: { power: +15, happy: -3, money: -10 } },
      { id: "ignore", emoji: "🍕", text: "그냥 피자 시킴", grade: "bad",
        effects: { happy: +5, power: -10 },
        narratives: ["미래의 본인이 후회한다."] },
      { id: "yoga", emoji: "🧘", text: "요가/명상", grade: "good",
        effects: { power: +8, happy: +10, intel: +3 } },
      { id: "shaman", emoji: "🔮", text: "용한 무당 추천 받음", grade: "crit",
        effects: { money: -20 },
        outcomes: [
          { chance: 0.2, effects: { happy: +12, luck: +10 }, narrative: "왠지 모르게 몸이 괜찮아졌다." },
          { chance: 0.8, effects: { money: -80, intel: -3 }, narrative: "사기였다." },
        ] },
    ],
  },
  {
    id: "midlife_career_pivot",
    stage: "midlife",
    emoji: "🎯",
    title: "인생 2막",
    desc: "지금 하던 거 말고 다른 거 해볼까?",
    choices: [
      { id: "stream_late", emoji: "🎥", text: "늦깎이 스트리머", grade: "crit", route: "streamer",
        effects: { internet: +10 },
        outcomes: [
          { chance: 0.05, effects: { internet: +25, money: +200, happy: +20 }, narrative: "🌟 아저씨 인기 폭발. 새로운 인생 시작." },
          { chance: 0.2, effects: { internet: +15, money: +50 }, narrative: "아저씨 콘텐츠가 의외로 떡상." },
          { chance: 0.75, effects: { happy: -3 }, narrative: "동접 5명. 4명은 가족." },
        ] },
      { id: "open_shop", emoji: "🍜", text: "자영업 (식당)", grade: "mid",
        effects: { money: -50, power: -5 },
        outcomes: [
          { chance: 0.4, effects: { money: +120, social: +6 }, narrative: "맛집으로 소문났다." },
          { chance: 0.6, effects: { money: -80, happy: -8 }, narrative: "권리금만 날렸다." },
        ] },
      { id: "stay", emoji: "💼", text: "그대로 살기", grade: "good",
        effects: { money: +30, happy: +3 } },
      { id: "gigolo", emoji: "🎻", text: "갑자기 음악 시작", grade: "crit",
        effects: { happy: +10 },
        outcomes: [
          { chance: 0.1, effects: { money: +150, social: +12 }, narrative: "트로트 신인왕. 인생이 또 떴다." },
          { chance: 0.9, effects: { money: -25 }, narrative: "취미로 끝났다. 그래도 즐거웠다." },
        ] },
    ],
  },
  {
    id: "midlife_lottery",
    stage: "midlife",
    emoji: "🎰",
    title: "복권 구매",
    desc: "그냥 한 번",
    choices: [
      { id: "buy", emoji: "🎟️", text: "산다", grade: "crit",
        effects: { money: -3 },
        outcomes: [
          { chance: 0.0005, effects: { money: +9999, happy: +50, luck: +50 }, narrative: "🌟🌟🌟 1등 당첨! 99억! 인생 종료 + 새 인생 시작!" },
          { chance: 0.005, effects: { money: +500, happy: +25, luck: +20 }, narrative: "🌟 2등! 1억!" },
          { chance: 0.05, effects: { money: +50, happy: +10 }, narrative: "5등! 치킨값 정도." },
          { chance: 0.9445, effects: {}, narrative: "꽝. 늘 그랬듯이." },
        ] },
      { id: "skip", emoji: "🚶", text: "안 산다", grade: "good",
        effects: { intel: +2 } },
    ],
  },
  {
    id: "midlife_alien",
    stage: "midlife",
    emoji: "👽",
    title: "외계인과의 조우",
    desc: "새벽 4시 산책 중 빛나는 물체가 너를 호출했다",
    choices: [
      { id: "go", emoji: "🛸", text: "따라간다", grade: "crit", route: "alien",
        outcomes: [
          { chance: 0.05, effects: { intel: +30, happy: +25, money: +500, internet: +20, luck: +30 }, narrative: "🌟 외계 기술 제공받음. 인류의 지도자." },
          { chance: 0.45, effects: { intel: +10, internet: +10, happy: +5 }, narrative: "기억은 흐릿한데 집에 돌아왔을 때 통장에 30만원 더 있었다." },
          { chance: 0.5, effects: { happy: -15, intel: -5, social: -10 }, narrative: "꿈이었다. 단순한 새벽 환각. 또는...?" },
        ] },
      { id: "post", emoji: "📱", text: "유튜브에 라이브", grade: "crit", route: "streamer",
        effects: { internet: +6 },
        outcomes: [
          { chance: 0.3, effects: { internet: +30, money: +150 }, narrative: "조회수 1억. UFO 채널이 됐다." },
          { chance: 0.7, effects: { happy: -8, social: -5 }, narrative: "광인 취급받았다." },
        ] },
      { id: "run", emoji: "🏃", text: "도망친다", grade: "mid",
        effects: { power: +5, happy: -3 } },
    ],
  },
  {
    id: "midlife_old_friend",
    stage: "midlife",
    emoji: "🍷",
    title: "동창회",
    desc: "20년 만에 동창들. 다들 빠짐없이 자랑 중",
    choices: [
      { id: "brag", emoji: "💎", text: "맞불 — 자랑 풀가동", grade: "crit",
        outcomes: [
          { chance: 0.4, effects: { happy: +12, social: +6 }, narrative: "1등 자랑꾼이 됐다." },
          { chance: 0.6, effects: { happy: -8, social: -8 }, narrative: "허세 들통. 한동안 동창 단톡 무시당했다." },
        ] },
      { id: "humble", emoji: "🙏", text: "겸손하게 듣기만", grade: "good",
        effects: { intel: +5, social: +3, happy: -3 } },
      { id: "leave", emoji: "🚶", text: "1차만 마시고 탈출", grade: "good",
        effects: { intel: +3, happy: +5, money: -8 } },
      { id: "old_love", emoji: "💔", text: "옛 첫사랑이 옆자리", grade: "crit",
        effects: { happy: +5 },
        outcomes: [
          { chance: 0.3, effects: { happy: +15, social: +5 }, narrative: "재회. 인생이 또 한 번 떨렸다." },
          { chance: 0.7, effects: { happy: -10, social: -3 }, narrative: "기억보다 많이 변했다. 환상이 깨졌다." },
        ] },
    ],
  },
  {
    id: "midlife_parents",
    stage: "midlife",
    emoji: "🏥",
    title: "부모님 입원",
    desc: "병원에서 연락이 왔다",
    choices: [
      { id: "all_in", emoji: "🤝", text: "병간호 풀가동", grade: "good",
        effects: { money: -50, happy: -8, power: -10, social: +6 } },
      { id: "money_only", emoji: "💸", text: "돈만 보냄", grade: "mid",
        effects: { money: -80, happy: -3, social: -3 } },
      { id: "split", emoji: "👨‍👩‍👧", text: "형제들과 분담", grade: "good",
        effects: { money: -25, happy: -3, social: +3, intel: +3 } },
    ],
  },
  {
    id: "midlife_late_yolo",
    stage: "midlife",
    emoji: "🎰",
    title: "마지막 불꽃",
    desc: "통장 잔고를 다 본 그 순간 — 한 번만 더",
    choices: [
      { id: "casino", emoji: "🎲", text: "강원도행", grade: "crit",
        effects: { money: -30 },
        outcomes: [
          { chance: 0.03, effects: { money: +800, happy: +25, luck: +20 }, narrative: "🌟 잭팟. 인생이 한 번 더 떠올랐다." },
          { chance: 0.97, effects: { money: -100, happy: -15 }, narrative: "그럴 줄 알았다. 카드값까지 빠짐." },
        ] },
      { id: "travel", emoji: "✈️", text: "혼자 여행", grade: "good",
        effects: { money: -25, happy: +18, intel: +3 } },
      { id: "save", emoji: "🏦", text: "통장에 묶음", grade: "good",
        effects: { money: +15, happy: -3 } },
      { id: "monk", emoji: "🛕", text: "절에 들어감", grade: "mid",
        effects: { happy: +20, money: -10, social: -10, intel: +5 },
        narratives: ["속세를 떠난 자의 마음은 가볍다."] },
    ],
  },

  // ============================================================
  // ★★★ v20260514_1 확장 — 로맨스 / SNS / 진로 / 특수 / 장기이벤트
  // ============================================================

  // ----- TEEN 로맨스 (성별 무관, 다양한 상대) -----
  {
    id: "teen_first_love",
    stage: "teen",
    type: "special",
    emoji: "💘",
    title: "학교 축제 — 첫 고백",
    desc: "체육관 뒤편. 누구에게 고백할 것인가? (안 할 수도 있다)",
    weight: 0.9,
    choices: [
      { id: "jieun", emoji: "📚", text: "지은 — 공부 1등", grade: "good",
        effects: { happy: +6, intel: +3 },
        relation: { romance: "지은" },
        outcomes: [
          { chance: 0.5, effects: { happy: +10, intel: +5 }, narrative: "성공. 도서관 데이트가 시작됐다." },
          { chance: 0.5, effects: { happy: -8, social: -3 }, narrative: "차였다. 도서관이 한동안 어색했다.", relation: { breakup: true } },
        ] },
      { id: "minho", emoji: "🏀", text: "민호 — 농구부 주장", grade: "good",
        effects: { happy: +5, power: +3 },
        relation: { romance: "민호" },
        outcomes: [
          { chance: 0.45, effects: { happy: +12, power: +5 }, narrative: "성공. 농구장에서 같이 뛰게 됐다." },
          { chance: 0.55, effects: { happy: -6, social: -2 }, narrative: "친구로 지내자고 했다.", relation: { breakup: true, friend: "민호", delta: +20 } },
        ] },
      { id: "seoyeon", emoji: "🎙️", text: "서연 — 방송부", grade: "good",
        effects: { happy: +5, internet: +5 },
        relation: { romance: "서연" },
        outcomes: [
          { chance: 0.4, effects: { happy: +10, internet: +8 }, narrative: "성공. 학교 방송에서 너 이름이 자주 나온다." },
          { chance: 0.6, effects: { happy: -8, internet: -3 }, narrative: "전교생이 알았다. 흑역사 갱신.", relation: { breakup: true }, flag: { add: ["public_humiliation"] } },
        ] },
      { id: "taejun", emoji: "🏛️", text: "태준 — 부잣집", grade: "mid",
        effects: { social: +3 },
        relation: { romance: "태준" },
        outcomes: [
          { chance: 0.35, effects: { happy: +8, money: +30, social: +5 }, narrative: "성공. 운전기사가 너를 데리러 오기 시작했다." },
          { chance: 0.65, effects: { happy: -10, social: -5 }, narrative: "급이 다르다며 거절당했다.", relation: { breakup: true } },
        ] },
      { id: "skip", emoji: "🚪", text: "안 한다", grade: "mid",
        effects: { intel: +3 },
        narratives: ["혼자가 편하다. 진심이다. 아마도."] },
    ],
  },
  {
    id: "teen_career_advice",
    stage: "teen",
    type: "special",
    emoji: "🧭",
    title: "진로상담",
    desc: "선생님이 너의 인생 항로를 묻는다",
    weight: 1.0,
    choices: [
      { id: "study", emoji: "📚", text: "공부 — 대학 진학", grade: "good",
        effects: { intel: +8, happy: -3 },
        flag: { add: ["track_study"] },
        route: "student",
        narratives: ["엄마가 좋아한다. 학원이 늘었다."] },
      { id: "art", emoji: "🎨", text: "예술 — 미술/음악/문학", grade: "good",
        effects: { happy: +6, intel: +4, money: -5 },
        flag: { add: ["track_art"] },
        route: "artist",
        narratives: ["엄마가 한숨을 쉬었다. 그래도 손은 멈추지 않았다."] },
      { id: "sports", emoji: "🏃", text: "운동 — 체육 특기생", grade: "good",
        effects: { power: +10, intel: -3 },
        flag: { add: ["track_sports"] },
        route: "athlete",
        narratives: ["새벽 6시 기상이 시작됐다."] },
      { id: "stream", emoji: "📺", text: "방송 — 학교 자퇴하고 풀타임", grade: "crit",
        effects: { internet: +8, intel: -5, social: -3 },
        flag: { add: ["track_stream"] },
        route: "streamer",
        outcomes: [
          { chance: 0.2, effects: { internet: +15, money: +60 }, narrative: "초반 떡상. 부모님 입을 다물게 했다." },
          { chance: 0.8, effects: { happy: -8, money: -20 }, narrative: "조회수 두 자리. 부모님이 매일 한숨을 쉬었다." },
        ] },
      { id: "lazy", emoji: "💤", text: "그냥 살래요", grade: "bad",
        effects: { happy: +5, intel: -5, social: -3 },
        flag: { add: ["track_lazy"] },
        narratives: ["선생님이 시선을 피했다."] },
    ],
  },
  {
    id: "teen_festival_stage",
    stage: "teen",
    type: "normal",
    emoji: "🎭",
    title: "학교 축제 무대",
    desc: "동아리에서 무대 한 자리가 비었다",
    choices: [
      { id: "dance", emoji: "💃", text: "댄스 무대", grade: "good",
        effects: { social: +6, power: +3, happy: +5 },
        narratives: ["인스타에 동영상 100개가 올라왔다."] },
      { id: "guitar", emoji: "🎸", text: "밴드 — 기타", grade: "good",
        effects: { happy: +6, social: +4, intel: +2 },
        route: "artist",
        narratives: ["감성 한 줌. 후배들이 따라하기 시작했다."] },
      { id: "mc", emoji: "🎤", text: "MC", grade: "good",
        effects: { social: +8, internet: +3 },
        narratives: ["전교생 앞에서 식은땀. 하지만 결국 박수받았다."] },
      { id: "watch", emoji: "👀", text: "구경만", grade: "mid",
        effects: { happy: +2 } },
    ],
  },

  // ----- ADULT 로맨스 -----
  {
    id: "adult_blind_date",
    stage: "adult",
    type: "special",
    emoji: "🍷",
    title: "소개팅",
    desc: "친구가 자신감 있게 추천한 사람. 결과는?",
    weight: 0.9,
    choices: [
      { id: "go_for_it", emoji: "💞", text: "적극적으로 어필", grade: "crit",
        effects: { happy: +3 },
        outcomes: [
          { chance: 0.4, effects: { happy: +15, social: +8 }, narrative: "잘 됐다. 다음 약속 잡혔다.", relation: { romance: "소개팅 상대" } },
          { chance: 0.6, effects: { happy: -10, social: -5 }, narrative: "과했다. 카톡 차단당했다.", flag: { add: ["awkward_history"] } },
        ] },
      { id: "play_cool", emoji: "😎", text: "쿨하게 — 밀당", grade: "good",
        effects: { social: +3 },
        outcomes: [
          { chance: 0.5, effects: { happy: +10, social: +5 }, narrative: "역대급 호감. 자연스럽게 연인이 됐다.", relation: { romance: "소개팅 상대" } },
          { chance: 0.5, effects: { happy: -3 }, narrative: "관심 없다고 오해받았다." },
        ] },
      { id: "no_show", emoji: "🏃", text: "약속 직전 도망", grade: "bad",
        effects: { happy: -3, social: -10 },
        narratives: ["친구가 한 달 동안 연락 안 받았다."] },
    ],
  },
  {
    id: "adult_old_flame",
    stage: "adult",
    type: "normal",
    emoji: "💌",
    title: "옛 인연이 보낸 카톡",
    desc: "한참 잊고 살았던 그 이름. 1시간째 답장을 못 보내고 있다",
    relationRequired: { romance: false }, // 현재 솔로일 때만 — 실은 항상 패스
    choices: [
      { id: "reply", emoji: "💬", text: "답장한다", grade: "good",
        effects: { happy: +5 },
        outcomes: [
          { chance: 0.5, effects: { happy: +12, social: +5 }, narrative: "다시 시작됐다. 이번엔 다를 거다.", relation: { romance: "그때 그 사람" } },
          { chance: 0.5, effects: { happy: -8 }, narrative: "그냥 안부였다. 마음만 흔들렸다." },
        ] },
      { id: "block", emoji: "🚫", text: "차단", grade: "good",
        effects: { intel: +5, happy: +2 },
        narratives: ["과거는 과거다. 어른의 결정."] },
      { id: "spy", emoji: "🕵️", text: "프로필만 1시간 보기", grade: "mid",
        effects: { happy: -5, internet: +3 },
        narratives: ["스토킹 한 발 직전. 잠은 못 잤다."] },
    ],
  },
  {
    id: "adult_propose",
    stage: "adult",
    type: "special",
    emoji: "💍",
    title: "프로포즈",
    desc: "연인과의 분기점. 어떻게 할 것인가",
    weight: 1.2,
    relationRequired: { romance: true },
    choices: [
      { id: "propose", emoji: "💍", text: "결혼하자", grade: "crit",
        effects: { happy: +12, money: -100, social: +8 },
        flag: { add: ["married"] },
        outcomes: [
          { chance: 0.7, effects: { happy: +15, social: +5 }, narrative: "수락. 결혼식 준비 시작." },
          { chance: 0.3, effects: { happy: -25, social: -10 }, narrative: "거절. 관계가 어색해졌다.", relation: { breakup: true } },
        ] },
      { id: "live_together", emoji: "🏠", text: "동거만 하자", grade: "good",
        effects: { happy: +8, money: -30 },
        flag: { add: ["cohabit"] },
        narratives: ["가구 사러 갔다가 첫 싸움이 시작됐다."] },
      { id: "wait", emoji: "⏳", text: "좀 더 만나보자", grade: "mid",
        effects: { happy: +2, intel: +3 } },
      { id: "breakup_now", emoji: "💔", text: "끝낸다", grade: "bad",
        effects: { happy: -15, social: -5 },
        relation: { breakup: true },
        narratives: ["속이 시원했다. 며칠은."] },
    ],
  },
  {
    id: "adult_baby",
    stage: "adult",
    type: "special",
    emoji: "👶",
    title: "아기 소식",
    desc: "예상보다 일찍 찾아온 변화",
    weight: 1.0,
    relationRequired: { romance: true },
    choices: [
      { id: "raise", emoji: "🍼", text: "키운다", grade: "good",
        effects: { happy: +10, money: -80, power: -5 },
        flag: { add: ["parent", "young_parent"] },
        route: "parent",
        narratives: ["새벽 3시 수유. 인생이 통째로 바뀌었다."] },
      { id: "wait_more", emoji: "💼", text: "지금은 아니다 — 일에 집중", grade: "mid",
        effects: { happy: -5, money: +20, intel: +3 },
        flag: { add: ["delayed_family"] } },
    ],
  },

  // ----- ADULT 진로 갈림길 -----
  {
    id: "adult_grad_school",
    stage: "adult",
    type: "special",
    emoji: "🎓",
    title: "대학원 진학",
    desc: "교수님이 손짓하셨다. 인생을 2년 더 통째로 갈아넣을 시간",
    weight: 0.8,
    flagRequired: ["track_study"],
    choices: [
      { id: "phd", emoji: "🎓", text: "박사까지 — 풀세트", grade: "crit",
        effects: { intel: +20, happy: -8, money: -40 },
        flag: { add: ["elite_school"] },
        route: "student",
        narratives: ["논문 통과. 머리카락은 통과하지 못했다."] },
      { id: "master", emoji: "📜", text: "석사만", grade: "good",
        effects: { intel: +10, money: -15 },
        flag: { add: ["elite_school"] } },
      { id: "drop", emoji: "🏃", text: "포기하고 취업", grade: "mid",
        effects: { money: +20, intel: -3, social: +3 },
        route: "worker",
        flag: { add: ["corp_track"] } },
    ],
  },
  {
    id: "adult_startup_offer",
    stage: "adult",
    type: "special",
    emoji: "🚀",
    title: "스타트업 제안",
    desc: "친구가 같이 창업하자고 한다. 통장은 텅텅. 꿈은 거대",
    weight: 0.9,
    choices: [
      { id: "go_all_in", emoji: "💎", text: "올인 — 회사 그만두고 합류", grade: "crit",
        effects: { money: -50, happy: +3, intel: +5 },
        relation: { friend: "공동창업자", delta: +30 },
        longTerm: { resultEventId: "lt_startup_result", after: 2 },
        route: "ai",
        narratives: ["사업자등록증 발급 받았다. 손이 떨렸다."] },
      { id: "side", emoji: "🌙", text: "사이드로만 도와줌", grade: "good",
        effects: { intel: +5, happy: -3 },
        relation: { friend: "공동창업자", delta: +10 } },
      { id: "decline", emoji: "🙅", text: "거절", grade: "mid",
        effects: { intel: +3, happy: +2 },
        relation: { friend: "공동창업자", delta: -10 } },
    ],
  },
  {
    id: "adult_chzzk_offer",
    stage: "adult",
    type: "special",
    emoji: "📺",
    title: "치지직 계약 제안",
    desc: "대형 플랫폼이 너에게 손을 내밀었다",
    weight: 1.0,
    choices: [
      { id: "sign", emoji: "💸", text: "계약 — 풀타임 스트리머", grade: "crit",
        effects: { money: +80, internet: +15, happy: +5 },
        flag: { add: ["chzzk_contract"] },
        route: "streamer",
        longTerm: { resultEventId: "lt_stream_result", after: 3 },
        narratives: ["엄마한테 말 못한 채 사인했다."] },
      { id: "negotiate", emoji: "🤝", text: "조건 협상", grade: "good",
        effects: { money: +40, internet: +8 },
        outcomes: [
          { chance: 0.5, effects: { money: +50, social: +5 }, narrative: "조건 더 받았다. 협상의 신.", flag: { add: ["chzzk_contract"] }, route: "streamer" },
          { chance: 0.5, effects: { money: -10, social: -3 }, narrative: "테이블에서 거절당했다." },
        ] },
      { id: "decline_offer", emoji: "🚪", text: "거절 — 자유롭게 살래", grade: "good",
        effects: { happy: +8, intel: +3 },
        narratives: ["조회수보다 자유."] },
    ],
  },
  {
    id: "adult_ai_creator",
    stage: "adult",
    type: "special",
    emoji: "🤖",
    title: "AI 서비스 출시",
    desc: "주말 동안 만든 AI 챗봇이 입소문을 타기 시작했다",
    weight: 0.8,
    choices: [
      { id: "scale", emoji: "🚀", text: "투자받고 스케일업", grade: "crit",
        effects: { money: -30, intel: +10 },
        flag: { add: ["ai_creator"] },
        route: "ai",
        longTerm: { resultEventId: "lt_ai_result", after: 2 },
        narratives: ["VC 미팅 다섯 번. 정장 한 번도 안 입었다."] },
      { id: "indie", emoji: "🏝️", text: "혼자 인디로 — 광고 수익만", grade: "good",
        effects: { money: +50, internet: +10 },
        route: "ai",
        flag: { add: ["ai_creator"] },
        narratives: ["월 매출 1천만. 잠은 잘 잤다."] },
      { id: "kill", emoji: "💀", text: "서비스 닫음", grade: "bad",
        effects: { intel: +2, happy: -5 },
        narratives: ["서버 비용이 무서웠다."] },
    ],
  },

  // ----- ADULT SNS / 인터넷 반응 -----
  {
    id: "adult_viral_post",
    stage: "adult",
    type: "special",
    emoji: "🔥",
    title: "내 게시물이 떡상",
    desc: "출근길에 올린 글 — 좋아요 12만",
    weight: 0.7,
    choices: [
      { id: "ride", emoji: "📱", text: "흐름 타고 SNS 전업", grade: "crit",
        effects: { internet: +15, social: +5, intel: -3 },
        flag: { add: ["viral_history"] },
        route: "influencer",
        outcomes: [
          { chance: 0.4, effects: { money: +120, internet: +10 }, narrative: "브랜드 협찬 줄섰다." },
          { chance: 0.6, effects: { money: +20, happy: -5 }, narrative: "흐름이 빨리 식었다. 그래도 한 줌 남았다." },
        ] },
      { id: "delete", emoji: "🗑️", text: "관심 부담 — 삭제", grade: "good",
        effects: { intel: +5, happy: +3 } },
      { id: "milk", emoji: "💰", text: "광고만 받고 끝", grade: "good",
        effects: { money: +30, internet: +5 } },
    ],
  },
  {
    id: "adult_internet_drama",
    stage: "adult",
    type: "special",
    emoji: "🚨",
    title: "인터넷 논란 발생",
    desc: "예전 게시물이 박제됐다. 디시 핫게 1위",
    weight: 0.7,
    flagRequired: ["viral_history"],
    choices: [
      { id: "apologize", emoji: "🙇", text: "공식 사과", grade: "good",
        effects: { social: -8, internet: -10, happy: -5 },
        flag: { add: ["controversy_apology"] },
        narratives: ["고개 숙인 30초 영상. 댓글 1만 개."] },
      { id: "fight", emoji: "👊", text: "맞불 — 사이다 반박", grade: "crit",
        effects: { internet: +5 },
        outcomes: [
          { chance: 0.3, effects: { internet: +20, social: +5 }, narrative: "오히려 팬 늘었다. 전화위복.", flag: { add: ["sympathy_arc"] } },
          { chance: 0.7, effects: { internet: -25, social: -15, happy: -10 }, narrative: "기름 부었다. 검색어 1위.", flag: { add: ["cancelled"] } },
        ] },
      { id: "go_dark", emoji: "🕳️", text: "잠수 — 모든 계정 폐쇄", grade: "good",
        effects: { internet: -15, happy: +8, intel: +3 },
        narratives: ["디지털 디톡스 강제 시작."] },
    ],
  },
  {
    id: "adult_dm_fame",
    stage: "adult",
    type: "normal",
    emoji: "💌",
    title: "DM 폭주",
    desc: "팔로워가 만 단위가 되자 모르는 사람들이 가득",
    relationRequired: { friendsMin: 0 }, // 항상 가능
    choices: [
      { id: "respond_all", emoji: "🤖", text: "전부 답해줌 — 팬 서비스", grade: "good",
        effects: { social: +5, internet: +5, intel: -3 } },
      { id: "exclusive", emoji: "🔒", text: "유료 멤버십 오픈", grade: "crit",
        effects: { money: +40, social: -3, internet: +3 },
        flag: { add: ["paid_member"] } },
      { id: "ghost", emoji: "👻", text: "전부 무시", grade: "mid",
        effects: { happy: +3, internet: -3 } },
    ],
  },

  // ----- ADULT 성별 분기 (이벤트만) -----
  {
    id: "adult_military",
    stage: "adult",
    type: "normal",
    emoji: "🪖",
    title: "입대",
    desc: "통지서가 왔다. 2년을 어떻게 보낼까",
    genderRequired: "M",
    choices: [
      { id: "serious", emoji: "🎖️", text: "성실히 — 진급 노림", grade: "good",
        effects: { power: +12, social: +5, intel: +3, happy: -5 },
        flag: { add: ["served"] },
        narratives: ["분대장이 됐다. 어른이 됐다."] },
      { id: "casual", emoji: "😴", text: "그냥저냥 — 시간 흐름만", grade: "mid",
        effects: { power: +5, happy: -3 },
        flag: { add: ["served"] } },
      { id: "studying", emoji: "📚", text: "사이버지식인 — 자격증 폭주", grade: "good",
        effects: { intel: +10, internet: +5, power: +3 },
        flag: { add: ["served", "self_study"] } },
    ],
  },
  {
    id: "adult_career_pause",
    stage: "adult",
    type: "normal",
    emoji: "🌸",
    title: "커리어 단절 위기",
    desc: "사회가 묻는다. 출산휴직? 복귀? 어떻게 할 것인가",
    genderRequired: "F",
    flagRequired: ["parent"],
    choices: [
      { id: "stay_home", emoji: "🏠", text: "전업 육아 — 풀타임", grade: "good",
        effects: { happy: +8, money: -30, social: -5 },
        flag: { add: ["full_parent"] } },
      { id: "return", emoji: "💼", text: "복귀 — 빠르게", grade: "crit",
        effects: { money: +40, intel: +5, happy: -8 },
        flag: { add: ["working_parent"] },
        narratives: ["커피로 버텼다. 시급보다 카페인이 비쌌다."] },
      { id: "freelance", emoji: "💻", text: "프리랜서 전환", grade: "good",
        effects: { money: +20, happy: +3, intel: +3 },
        flag: { add: ["freelance_parent"] } },
    ],
  },

  // ----- ADULT 친구/인맥 -----
  {
    id: "adult_friend_business",
    stage: "adult",
    type: "normal",
    emoji: "🤝",
    title: "친구가 돈 빌려달라",
    desc: "절친이 떨리는 목소리로 전화했다",
    choices: [
      { id: "lend", emoji: "💰", text: "그냥 줌 — 우정값", grade: "good",
        effects: { money: -50, social: +5 },
        relation: { friend: "절친", delta: +40 },
        outcomes: [
          { chance: 0.5, effects: { money: +60, social: +5 }, narrative: "갚았다. 평생 친구." },
          { chance: 0.5, effects: { money: 0, happy: -8 }, narrative: "잠수탔다. 인스타에서만 보인다.", relation: { foe: "절친" } },
        ] },
      { id: "contract", emoji: "📜", text: "차용증 받고 빌려줌", grade: "good",
        effects: { money: -50, intel: +3 },
        relation: { friend: "절친", delta: +10 },
        narratives: ["우정에 시스템을 끼얹었다."] },
      { id: "refuse", emoji: "🙅", text: "안 빌려줌", grade: "mid",
        effects: { intel: +5 },
        relation: { friend: "절친", delta: -25 } },
    ],
  },
  {
    id: "adult_squad_trip",
    stage: "adult",
    type: "normal",
    emoji: "✈️",
    title: "친구들과 해외여행",
    desc: "단톡에 비행기 표 캡처가 떴다",
    choices: [
      { id: "join", emoji: "🛫", text: "지른다", grade: "good",
        effects: { money: -40, happy: +12, social: +8, intel: +3 },
        relation: { friend: "여행 크루", delta: +30 } },
      { id: "skip_save", emoji: "💸", text: "이번엔 패스 — 저축", grade: "mid",
        effects: { money: +20, social: -5 },
        relation: { friend: "여행 크루", delta: -10 } },
      { id: "remote", emoji: "💻", text: "워케이션으로 합류", grade: "good",
        effects: { money: -20, happy: +8, social: +3, intel: +5 },
        flag: { add: ["remote_worker"] } },
    ],
  },

  // ----- ADULT 특수: 코인 -----
  {
    id: "adult_yolo_invest",
    stage: "adult",
    type: "special",
    emoji: "🎢",
    title: "위험한 투자 제안",
    desc: "지인이 '확실'하다고 했다. 마진 30배",
    weight: 0.9,
    choices: [
      { id: "all_in_coin", emoji: "💎", text: "영끌 — 전재산 투자", grade: "crit",
        effects: { money: -150 },
        route: "crypto",
        longTerm: { resultEventId: "lt_crypto_result", after: 2 },
        narratives: ["엔터 키를 누른 손이 떨렸다."] },
      { id: "small", emoji: "🪙", text: "용돈만 살짝", grade: "good",
        effects: { money: -20, intel: +2 },
        route: "crypto",
        longTerm: { resultEventId: "lt_crypto_small", after: 2 } },
      { id: "no", emoji: "🚫", text: "거절", grade: "good",
        effects: { intel: +5, money: +5 },
        narratives: ["다음 날 그 코인이 +200%. 화면 끄고 잤다."] },
    ],
  },

  // ----- MIDLIFE 특수 -----
  {
    id: "midlife_child_career",
    stage: "midlife",
    type: "special",
    emoji: "🎒",
    title: "자녀의 진로 결정",
    desc: "내 아이가 묻는다. 뭘 해야 돼?",
    weight: 1.0,
    flagRequired: ["parent"],
    choices: [
      { id: "push_study", emoji: "📚", text: "공부 강요 — 학원 풀세트", grade: "mid",
        effects: { money: -60, happy: -3 },
        outcomes: [
          { chance: 0.4, effects: { money: +50, happy: +10, social: +5 }, narrative: "명문대 합격. 동네 자랑.", flag: { add: ["kid_elite"] } },
          { chance: 0.6, effects: { happy: -15, social: -5 }, narrative: "관계가 멀어졌다.", flag: { add: ["kid_distant"] } },
        ] },
      { id: "free", emoji: "🎨", text: "하고 싶은 거 해 — 응원만", grade: "good",
        effects: { happy: +8, money: -10 },
        flag: { add: ["kid_free"] } },
      { id: "biz", emoji: "💼", text: "물려준다 — 가업 합류", grade: "good",
        effects: { money: +30, happy: +3 },
        flag: { add: ["family_business"] } },
    ],
  },
  {
    id: "midlife_inherit",
    stage: "midlife",
    type: "special",
    emoji: "💰",
    title: "유산 — 통장에 8자리",
    desc: "예고 없이 어머니 친척이 남기고 갔다",
    weight: 0.5,
    choices: [
      { id: "save_inherit", emoji: "🏦", text: "적금으로 묶음", grade: "good",
        effects: { money: +200, intel: +3 } },
      { id: "splurge", emoji: "🏎️", text: "스포츠카 + 명품", grade: "crit",
        effects: { money: +100, happy: +20, social: -5 },
        flag: { add: ["luxury_life"] } },
      { id: "donate", emoji: "🤲", text: "기부", grade: "good",
        effects: { happy: +25, social: +15 },
        flag: { add: ["philanthropist"] },
        narratives: ["뉴스에 나왔다. 이름은 안 알렸다."] },
      { id: "travel_inherit", emoji: "🌍", text: "세계 여행 — 일 그만두고 출발", grade: "crit",
        effects: { money: -80, happy: +30, intel: +10 },
        route: "traveler",
        flag: { add: ["world_tour"] } },
    ],
  },

  // ============================================================
  // ★ LONGTERM 결과 이벤트 — 일반 풀에서 안 뽑힘, longTerm 큐에서만 fire
  // ============================================================
  {
    id: "lt_crypto_result",
    stage: "*",
    type: "longterm",
    emoji: "📊",
    title: "[장기] 그때 그 코인",
    desc: "영끌해서 넣었던 그 종목... 차트를 열어볼 시간",
    choices: [
      { id: "check_now", emoji: "📉", text: "결과 확인", grade: "mid",
        outcomes: [
          { chance: 0.15, effects: { money: +600, happy: +25, luck: +5 }, narrative: "🚀 10배. 인생이 한 번 더 떠올랐다." },
          { chance: 0.25, effects: { money: +120, happy: +8 }, narrative: "2배 됐다. 익절 잘했다." },
          { chance: 0.6, effects: { money: -120, happy: -15 }, narrative: "그럴 줄 알았다. 영끌의 끝.", flag: { add: ["coin_doom"] } },
        ] },
      { id: "ignore", emoji: "🫥", text: "안 본다", grade: "bad",
        effects: { money: -80, happy: -10 },
        narratives: ["몇 년 뒤 확인. 이미 0이었다.", "0이면 0이다."] },
    ],
  },
  {
    id: "lt_crypto_small",
    stage: "*",
    type: "longterm",
    emoji: "🪙",
    title: "[장기] 용돈 코인의 결과",
    desc: "심심해서 묶어둔 그 코인",
    choices: [
      { id: "see", emoji: "📈", text: "본다", grade: "mid",
        outcomes: [
          { chance: 0.2, effects: { money: +80, happy: +8 }, narrative: "4배. 짭짤하다." },
          { chance: 0.4, effects: { money: +25, happy: +3 }, narrative: "조금 벌었다." },
          { chance: 0.4, effects: { money: -20, happy: -3 }, narrative: "조금 잃었다. 학습비." },
        ] },
      { id: "skip_check", emoji: "💤", text: "관심 끔", grade: "mid",
        effects: { intel: +3 } },
    ],
  },
  {
    id: "lt_startup_result",
    stage: "*",
    type: "longterm",
    emoji: "🚀",
    title: "[장기] 스타트업의 운명",
    desc: "그때 그 창업 — 지금쯤 어떻게 됐을까",
    choices: [
      { id: "open_dashboard", emoji: "📊", text: "정산 확인", grade: "mid",
        outcomes: [
          { chance: 0.15, effects: { money: +400, happy: +20, intel: +10 }, narrative: "엑싯 성공. 친구랑 같이 부자가 됐다.", flag: { add: ["startup_win"] }, relation: { friend: "공동창업자", delta: +30 } },
          { chance: 0.35, effects: { money: +80, intel: +8 }, narrative: "유지는 한다. 월급도 받는다.", flag: { add: ["startup_meh"] } },
          { chance: 0.5, effects: { money: -100, happy: -15 }, narrative: "폐업. 친구와 사이도 끝.", relation: { foe: "공동창업자" }, flag: { add: ["startup_fail"] } },
        ] },
    ],
  },
  {
    id: "lt_stream_result",
    stage: "*",
    type: "longterm",
    emoji: "📺",
    title: "[장기] 치지직 계약 결과",
    desc: "계약 3년차. 너의 채널은?",
    choices: [
      { id: "check_stream", emoji: "🎬", text: "정산 확인", grade: "mid",
        outcomes: [
          { chance: 0.2, effects: { money: +400, internet: +20, happy: +15 }, narrative: "대기업 스트리머. 광고 줄섰다.", flag: { add: ["chzzk_star"] } },
          { chance: 0.4, effects: { money: +120, internet: +8 }, narrative: "중견. 먹고는 산다." },
          { chance: 0.4, effects: { money: -30, internet: -10, happy: -10 }, narrative: "계약 종료. 다시 0부터.", flag: { add: ["stream_burnout"] } },
        ] },
    ],
  },
  {
    id: "lt_ai_result",
    stage: "*",
    type: "longterm",
    emoji: "🤖",
    title: "[장기] AI 서비스의 운명",
    desc: "투자받은 그 AI — 3년이 지났다",
    choices: [
      { id: "check_ai", emoji: "📈", text: "현황 확인", grade: "mid",
        outcomes: [
          { chance: 0.18, effects: { money: +600, intel: +15, internet: +10 }, narrative: "유니콘 등극. 그가 곧 특이점이었다.", flag: { add: ["ai_unicorn"] } },
          { chance: 0.42, effects: { money: +150, intel: +8 }, narrative: "안정적 흑자. 직원 12명." },
          { chance: 0.4, effects: { money: -150, happy: -15, intel: +3 }, narrative: "투자금 다 태웠다. 다음 라운드는 없다.", flag: { add: ["ai_burn"] } },
        ] },
    ],
  },
];

// ============================================================
// 엔딩 정의 — 점수/루트 기반 매칭
// 매칭 우선순위: 위에서 아래로 — 위에 둔 엔딩이 먼저 매칭됨
// rarity: "hidden" | "rare" | "common"
// ============================================================
export const ENDINGS = [
  // 🌟 SUPER 엔딩 (특수, hidden)
  {
    id: "alien_chosen",
    title: "외계 의회 의장 엔딩",
    emoji: "🛸",
    badge: "COSMIC",
    rarity: "hidden",
    quote: "지구는 그가 선택한 변방의 행성에 불과했다. 진짜 일은 우주에서 시작되었다.",
    match: (s, r) => r.has("alien"),
  },
  {
    id: "space_emigrant",
    title: "우주 이민자 엔딩",
    emoji: "🚀",
    badge: "EXODUS",
    rarity: "hidden",
    quote: "그는 지구를 졸업했다. 다음 주소지: 화성 콜로니 4번 구역.",
    match: (s, r, ctx) => ctx?.flags?.has("world_tour") && r.has("traveler") && (s.luck >= 70 || s.intel >= 75),
  },
  {
    id: "ai_revolution",
    title: "AI 혁명 생존자 엔딩",
    emoji: "🤖",
    badge: "SINGULARITY",
    rarity: "hidden",
    quote: "특이점을 넘었을 때, 그는 이미 그 너머에 있었다.",
    match: (s, r, ctx) => ctx?.flags?.has("ai_unicorn"),
  },
  {
    id: "chzzk_empire",
    title: "치지직 대기업 엔딩",
    emoji: "📺",
    badge: "TYCOON",
    rarity: "rare",
    quote: "방송이 끝나도 알람이 멈추지 않았다. 그의 채팅창은 이제 한 도시였다.",
    match: (s, r, ctx) => ctx?.flags?.has("chzzk_star") && r.has("streamer"),
  },
  {
    id: "criminal",
    title: "수배자 엔딩",
    emoji: "🚓",
    badge: "WANTED",
    rarity: "rare",
    quote: "한순간의 욕심이 평생을 따라다녔다. 그의 얼굴은 공항 모니터에 박제되었다.",
    match: (s, r) => r.has("criminal"),
  },
  {
    id: "evil_overlord",
    title: "흑화 엔딩",
    emoji: "😈",
    badge: "FALLEN",
    rarity: "rare",
    quote: "선의는 비웃음으로 돌아왔다. 그래서 그는 거울을 깨고 다른 인생을 골랐다.",
    match: (s, r, ctx) => ctx?.flags?.has("cancelled") && (ctx?.relations?.foes?.length || 0) >= 2 && s.money >= 100,
  },
  {
    id: "lottery_god",
    title: "벼락부자 엔딩",
    emoji: "🎰",
    badge: "JACKPOT",
    rarity: "rare",
    quote: "아무도 그가 어떻게 돈을 벌었는지 묻지 않았다. 99억 앞에서는 모두가 침묵했다.",
    match: (s) => s.money >= 1000,
  },
  // 루트 엔딩
  {
    id: "crypto_king",
    title: "코인 재벌 엔딩",
    emoji: "💎",
    badge: "RICH",
    quote: "코인은 미신이 아니라 시스템이었다. 모두 비웃을 때 그는 손가락 하나로 계좌를 키웠다.",
    match: (s, r) => s.money >= 300 && r.has("crypto"),
  },
  {
    id: "stream_star",
    title: "인터넷 스타 엔딩",
    emoji: "📺",
    badge: "VIRAL",
    quote: "그의 방송은 매일 밤 수십만 명을 잠 못 들게 했다. 도네이션 알람이 자장가가 되었다.",
    match: (s, r) => s.internet >= 70 && r.has("streamer"),
  },
  {
    id: "idol_legend",
    title: "월클 아이돌 엔딩",
    emoji: "🎤",
    badge: "STAR",
    quote: "팬덤이 국경을 넘었다. 데뷔 때의 그 어색한 안무가 이제는 전설이 되었다.",
    match: (s, r) => r.has("idol") && s.social >= 70,
  },
  {
    id: "politician",
    title: "거물 정치인 엔딩",
    emoji: "🏛️",
    badge: "POWER",
    quote: "한때는 동네 선거 출마자였지만, 이제는 그의 이름이 교과서에 실린다.",
    match: (s, r) => r.has("politics") && s.social >= 60,
  },
  {
    id: "ai_mogul",
    title: "AI 사업가 엔딩",
    emoji: "🤖",
    badge: "TECH",
    quote: "그는 사람이 아닌 시스템을 길렀다. 그 시스템이 그의 노후를 책임지고 있다.",
    match: (s, r) => r.has("ai") && s.money >= 200,
  },
  {
    id: "athlete",
    title: "국가대표 엔딩",
    emoji: "🥇",
    badge: "PHYSICAL",
    quote: "땀은 거짓말을 하지 않았다. 시상대 위에서 모든 것이 보상받았다.",
    match: (s, r) => r.has("athlete") && s.power >= 80,
  },
  {
    id: "esports_legend",
    title: "e스포츠 레전드 엔딩",
    emoji: "🏆",
    badge: "LEGEND",
    rarity: "rare",
    quote: "키보드와 마우스로 세계 정상에 섰다. 부모님이 처음으로 게임을 칭찬했다.",
    match: (s, r) => r.has("gamer") && s.internet >= 70 && s.money >= 100,
  },
  {
    id: "artist_genius",
    title: "천재 예술가 엔딩",
    emoji: "🎨",
    badge: "MUSE",
    rarity: "rare",
    quote: "그의 작품 앞에서 사람들은 한참을 멈춰 있었다. 설명할 수 없는 무언가가 있었다.",
    match: (s, r) => r.has("artist") && s.intel >= 70 && s.happy >= 55,
  },
  {
    id: "gym_god",
    title: "헬창 GOAT 엔딩",
    emoji: "🏋️",
    badge: "BEAST",
    rarity: "rare",
    quote: "그의 인생은 단순했다 — 들 수 있는가, 없는가. 그게 전부였다. 그리고 그는 다 들었다.",
    match: (s, r) => r.has("athlete") && s.power >= 90,
  },
  {
    id: "world_traveler",
    title: "자유로운 여행자 엔딩",
    emoji: "🏝️",
    badge: "FREEDOM",
    rarity: "rare",
    quote: "그의 여권은 다른 사람들의 이력서보다 두꺼웠다. 책상이 없는 인생도 인생이었다.",
    match: (s, r) => r.has("traveler") && s.happy >= 70,
  },
  {
    id: "happy_marriage",
    title: "행복한 결혼 엔딩",
    emoji: "💍",
    badge: "FAMILY",
    rarity: "common",
    quote: "통장은 조금 가벼웠지만 식탁은 항상 떠들썩했다. 그게 그가 고른 부유함이었다.",
    match: (s, r, ctx) => ctx?.flags?.has("married") && s.happy >= 60 && s.social >= 50,
  },
  {
    id: "young_parent",
    title: "청년 엄빠 엔딩",
    emoji: "👨‍👩‍👧",
    badge: "PARENT",
    rarity: "common",
    quote: "남들이 자유를 누릴 때 그는 새벽 분유를 탔다. 후회는 없었다. 졸렸을 뿐.",
    match: (s, r, ctx) => r.has("parent") && ctx?.flags?.has("young_parent") && s.happy >= 50,
  },
  {
    id: "trot_star",
    title: "트로트 신인왕 엔딩",
    emoji: "🎻",
    badge: "VOICE",
    rarity: "rare",
    quote: "마이크 한 자루로 인생 2막을 열었다. 시상식 트로피가 거실 한가운데 자리잡았다.",
    match: (s) => s.happy >= 70 && s.social >= 65 && s.money >= 100,
  },
  // 인생 결과 엔딩
  {
    id: "well_balanced",
    title: "이상적 시민 엔딩",
    emoji: "🌟",
    badge: "BALANCED",
    quote: "특별하진 않았지만 모든 영역이 평균 이상이었다. 사람들은 그를 \"그냥 잘 사는 사람\"이라고 불렀다.",
    match: (s) => s.happy >= 65 && s.money >= 80 && s.intel >= 65 && s.social >= 65 && s.power >= 65,
  },
  {
    id: "lazy_happy",
    title: "행복한 백수 엔딩",
    emoji: "🛏️",
    badge: "ZEN",
    quote: "통장은 가벼웠지만 마음은 깃털 같았다. 그의 하루는 햇볕과 라면으로 충분했다.",
    match: (s, r) => s.happy >= 75 && (r.has("neet") || s.money < 50),
  },
  {
    id: "corporate_overlord",
    title: "대기업 인간 엔딩",
    emoji: "🏢",
    badge: "EXEC",
    rarity: "common",
    quote: "그의 명함은 두꺼웠고, 미소는 매뉴얼이었다. 회사가 곧 그였고, 그가 곧 회사였다.",
    match: (s, r, ctx) => ctx?.flags?.has("corp_track") && s.money >= 200 && s.intel >= 55,
  },
  {
    id: "office_zombie",
    title: "야근 머신 엔딩",
    emoji: "💼",
    badge: "GRIND",
    rarity: "common",
    quote: "그는 매일 회사에 영혼을 조금씩 떼어주었다. 통장은 가득 찼지만 거울 속 얼굴은 처음 보는 사람이었다.",
    match: (s, r) => r.has("worker") && s.happy < 40 && s.money >= 100,
  },
  {
    id: "scholar",
    title: "조용한 지성인 엔딩",
    emoji: "📚",
    badge: "MIND",
    quote: "그는 시끄러운 세상에서 가장 조용한 도서관을 골랐다. 그 안에서 모든 답을 찾았다.",
    match: (s) => s.intel >= 80,
  },
  {
    id: "cult_leader",
    title: "사이비 교주 엔딩",
    emoji: "🕯️",
    badge: "FAITH",
    quote: "사람들은 그를 따랐다. 그 자신도 왜 따르는지 정확히 알지 못했다.",
    match: (s) => s.social >= 80 && s.money >= 200 && s.intel <= 50,
  },
  {
    id: "shaman_master",
    title: "전국구 무당 엔딩",
    emoji: "🔮",
    badge: "MYSTIC",
    quote: "그는 운명을 보았다고 했다. 진짜 본 건지, 본 척한 건지는 그 자신만 안다.",
    match: (s) => s.luck >= 80 && s.money >= 100,
  },
  {
    id: "bankrupt",
    title: "패가망신 엔딩",
    emoji: "🪦",
    badge: "WRECK",
    quote: "코인, 영끌, 그리고 또 코인. 다음 생에는 적금부터 해보라는 게 그의 마지막 한마디였다.",
    match: (s) => s.money <= -50,
  },
  {
    id: "social_zero",
    title: "사회성 제로 엔딩",
    emoji: "🐢",
    badge: "ALONE",
    quote: "그는 결국 가장 친한 친구가 자기 자신이라는 사실을 깨달았다. 나쁘지 않았다.",
    match: (s) => s.social <= 25,
  },
  {
    id: "lucky",
    title: "운빨 엔딩",
    emoji: "🍀",
    badge: "LUCKY",
    quote: "능력? 노력? 그런 거 없었다. 그냥 운이 좋았다. 그게 가장 큰 능력이었다.",
    match: (s) => s.luck >= 75,
  },
  {
    id: "influencer_doom",
    title: "박제된 인플루언서 엔딩",
    emoji: "📉",
    badge: "CANCELLED",
    rarity: "rare",
    quote: "그의 이름은 검색하지 말라고 했다. 그의 캡처는 영원했다.",
    match: (s, r, ctx) => ctx?.flags?.has("cancelled") && s.happy <= 45,
  },
  {
    id: "doom_internet",
    title: "인터넷 폐인 엔딩",
    emoji: "🖥️",
    badge: "TERMINAL",
    rarity: "common",
    quote: "그는 살아있다. 다만 와이파이가 끊기면 죽는다. 그게 그의 정의였다.",
    match: (s) => s.internet >= 85 && s.power <= 35,
  },
  {
    id: "solo_zen",
    title: "혼자가 좋아 엔딩",
    emoji: "🧘",
    badge: "SOLO",
    rarity: "common",
    quote: "연애는 안 했다. 친구도 적었다. 그러나 자기 자신과는 가장 친했다. 그걸로 충분했다.",
    match: (s, r, ctx) => !ctx?.relations?.romance && s.intel >= 65 && s.happy >= 60,
  },
  {
    id: "depression",
    title: "쓸쓸한 엔딩",
    emoji: "🌧️",
    badge: "GLOOM",
    quote: "어디서부터 잘못된 건지 끝까지 알 수 없었다. 그냥 그렇게 끝났다.",
    match: (s) => s.happy <= 25,
  },
  // 기본 엔딩 (무조건 매칭) — 마지막에 배치
  {
    id: "ordinary",
    title: "평범한 인생 엔딩",
    emoji: "🌥️",
    badge: "NORMAL",
    quote: "그저 그런 인생이었다. 하지만 인생은 원래 그저 그런 것이었을지도 모른다.",
    match: () => true,
  },
];

// ============================================================
// 심리분석 라인 — 스탯/루트별 추출
// ============================================================
export const ANALYSIS_LINES = [
  // 인터넷
  { when: (s) => s.internet >= 80, text: "와이파이가 끊기면 호흡이 곤란해지는 타입." },
  { when: (s) => s.internet >= 65, text: "인터넷에 너무 깊이 들어갔다. 와이파이가 곧 산소다." },
  { when: (s) => s.internet <= 25, text: "디지털 디톡스 챔피언. 밈을 잘 모른다." },
  // 돈
  { when: (s) => s.money >= 500, text: "이 정도면 다음 생도 자동 부자다." },
  { when: (s) => s.money >= 200, text: "돈 모으는 본능이 살아있다. 다음 생에도 부자일 듯." },
  { when: (s) => s.money <= -100, text: "신용불량 5년 코스. 인스타에 박제될 각." },
  { when: (s) => s.money <= -30, text: "코인만 안 했어도 중산층이었습니다." },
  // 행복
  { when: (s) => s.happy >= 85, text: "도파민 회로가 최강. 거의 부처급 행복도." },
  { when: (s) => s.happy >= 75, text: "도파민 회로가 매우 건강하다. 거의 행복 만수르." },
  { when: (s) => s.happy <= 30, text: "한숨 빈도가 0.5초당 1회. 휴식이 시급하다." },
  { when: (s) => s.happy <= 15, text: "이 인생 다시 살라고 하면 거부할 가능성 100%." },
  // 지능
  { when: (s) => s.intel >= 85, text: "지능이 인생의 모든 문제를 해결했다." },
  { when: (s) => s.intel >= 75, text: "지능이 밥 먹여줬다." },
  { when: (s) => s.intel <= 30, text: "본능형 인간. 머리보다 몸이 빨랐다." },
  { when: (s) => s.intel <= 15, text: "분명히 살아있는데 어떻게 살아있는지 미스터리." },
  // 사회성
  { when: (s) => s.social >= 80, text: "결혼식 사회 5번 본 사람." },
  { when: (s) => s.social >= 65, text: "어디에 가도 5분이면 새 친구를 만든다." },
  { when: (s) => s.social <= 25, text: "사회성은 낮지만 인터넷 적응력이 높습니다." },
  { when: (s) => s.social <= 15, text: "장례식에 본인 빼고 0명 참석 가능성 농후." },
  // 체력
  { when: (s) => s.power >= 85, text: "체력이 정신력을 이긴 사례." },
  { when: (s) => s.power >= 70, text: "지옥불도 버틸 코어." },
  { when: (s) => s.power <= 30, text: "엘리베이터 1층 차이도 망설인다." },
  { when: (s) => s.power <= 15, text: "택배 들 때마다 인생을 의심함." },
  // 운
  { when: (s) => s.luck >= 80, text: "신이 편애한다. 본인도 부담스러워한다." },
  { when: (s) => s.luck >= 65, text: "운으로 메우는 인생. 정작 실력은..." },
  { when: (s) => s.luck <= 25, text: "복권은 절대 사지 마세요. 인생이 충분히 도박이었습니다." },
  { when: (s) => s.luck <= 10, text: "복도에서 우산을 펴면 천장이 무너지는 타입." },
  // 루트 콤보
  { when: (_, r) => r.has("crypto") && r.has("streamer"), text: "코인 + 방송. 가장 위험한 조합을 모두 시도했다." },
  { when: (_, r) => r.has("neet") && r.has("crypto"), text: "백수 + 코인. 부모님 등골을 시즌 22로 연장 중." },
  { when: (_, r) => r.has("politics") && r.has("ai"), text: "정치 + AI. 미래 권력의 전형적 조합." },
  { when: (_, r) => r.has("idol") && r.has("streamer"), text: "스타 두 번 했다. 한 번도 어려운데." },
  { when: (_, r) => r.has("neet"), text: "당신은 도파민에 매우 취약한 타입입니다." },
  { when: (_, r) => r.has("ai"), text: "AI보다 한 발 앞서 살았다. 특이점은 본인이었다." },
  { when: (_, r) => r.has("criminal"), text: "전과기록이 이력서보다 길다." },
  { when: (_, r) => r.has("alien"), text: "지구가 답답했던 적이 있다고 한다. 의문의 1승." },
  // 일반
  { when: (s) => s.money >= 100 && s.happy <= 35, text: "돈은 있는데 웃을 일이 없다. 표본형 한국인." },
  { when: (s) => s.money <= 0 && s.happy >= 70, text: "통장은 비었지만 마음은 가득. 진정한 행복론자." },
  // ===== v20260514_1 신규: 관계/플래그/성별 기반 =====
  { when: (_s, _r, ctx) => ctx?.flags?.has("married"), text: "한 사람과 인생 정착. 의외로 가장 어려운 선택이었다." },
  { when: (_s, _r, ctx) => ctx?.flags?.has("cancelled"), text: "검색하면 박제된 사진이 나온다. 친구들은 모른 척했다." },
  { when: (_s, _r, ctx) => ctx?.flags?.has("startup_win"), text: "엑싯 한 번 해본 인간의 눈빛에는 다른 것이 있다." },
  { when: (_s, _r, ctx) => ctx?.flags?.has("ai_unicorn"), text: "그가 만든 시스템이 그보다 많이 일했다." },
  { when: (_s, _r, ctx) => ctx?.flags?.has("served"), text: "어른 도장 한 번 받고 왔다. 자랑할 일도, 후회할 일도 아니다." },
  { when: (_s, _r, ctx) => ctx?.flags?.has("world_tour"), text: "여권에 도장이 많다. 본인 이름은 자주 까먹는다." },
  { when: (_s, _r, ctx) => (ctx?.relations?.foes?.length || 0) >= 2, text: "그의 연락처에 차단번호가 정직원보다 많다." },
  { when: (_s, _r, ctx) => Object.keys(ctx?.relations?.friends || {}).length >= 3, text: "주변에 사람이 많다. 본인은 가끔 피곤하다고 한다." },
  { when: (_s, _r, ctx) => !ctx?.relations?.romance && ctx?.flags?.has("delayed_family"), text: "연애도 결혼도 미뤘다. 이유는 본인도 모른다고 한다." },
  { when: (_s, _r, ctx) => ctx?.flags?.has("public_humiliation"), text: "고등학교 동창들이 아직도 그 사건을 기억한다." },
  { when: (s, _r, ctx) => ctx?.flags?.has("coin_doom") && s.money <= 0, text: "차트 캡처가 그의 위패다." },
];
